In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from plotly import express as px
from plotly import graph_objects as go

In [ ]:
df=pd.read_csv("gandhinagar_properties_processed.csv")

In [3]:
pd.set_option('display.max_columns',None)

In [4]:
df.drop_duplicates(inplace=True)

In [5]:
df.head()

,Name,Location,Price (INR in Lakhs),Price_per_sqft,Area_sqft,Description,Property_URL,bedrooms,bathrooms,balconies,current_floor,total_floors,furnishing_status,Mapped_Area,facing,property_age_bucket,is_ready_to_move,is_built_up_area,is_carpet_area,is_super_built_up_area,property_type,luxury_score,location_advantage_score
0,"3 BHK Flatin Sargasan, Gandhinagar","Sargasan, Gandhinagar",126.00,4320.0,2916.0,Experience a new style of living with Altezza ...,https://www.99acres.com/3-bhk-bedroom-apartmen...,3.0,3.0,1.0,NaN,NaN,NaN,Sargasan,NaN,New,1,False,False,True,apartment,0.0,0.0
1,"3 BHK Flatin Pethapur, Gandhinagar","Pethapur, Gandhinagar",51.99,2962.0,1755.0,Experience a new style of living with Satyamev...,https://www.99acres.com/3-bhk-bedroom-apartmen...,3.0,3.0,2.0,NaN,NaN,NaN,Pethapur,NaN,New,0,False,False,True,apartment,0.0,0.0
2,"3 BHK Flatin Raysan, Gandhinagar","Raysan, Gandhinagar",97.00,5083.0,1908.0,This is your chance to a 3 bhk apartment / fla...,https://www.99acres.com/3-bhk-bedroom-apartmen...,3.0,3.0,2.0,NaN,NaN,NaN,Raysan,NaN,New,1,False,False,True,apartment,0.0,0.0
3,"3 BHK Flatin Raysan, Gandhinagar","Raysan, Gandhinagar",125.00,5669.0,2205.0,We are the proud owners of this 3 bhk apartmen...,https://www.99acres.com/3-bhk-bedroom-apartmen...,3.0,2.0,2.0,9.0,NaN,NaN,Raysan,NaN,New,1,False,True,False,apartment,0.0,0.0
4,"3 BHK Flatin Urjanagar 1, Randesan, Gandhinagar","Urjanagar 1, Randesan, Gandhinagar",79.00,4501.0,1755.0,Situated on the top floor (8th) of a mid-Rise ...,https://www.99acres.com/3-bhk-bedroom-apartmen...,3.0,3.0,1.0,8.0,NaN,unfurnished,Randesan,NaN,5-10 years,1,False,True,False,apartment,0.0,1.0

In [6]:
df.shape

(1683, 23)

In [7]:
df['Price (INR in Lakhs)'].describe()

count    1683.000000
mean      143.469020
std       212.732127
min         2.100000
25%        57.000000
50%        85.000000
75%       145.000000
max      3200.000000
Name: Price (INR in Lakhs), dtype: float64

In [8]:
df.columns

Index(['Name', 'Location', 'Price (INR in Lakhs)', 'Price_per_sqft',
       'Area_sqft', 'Description', 'Property_URL', 'bedrooms', 'bathrooms',
       'balconies', 'current_floor', 'total_floors', 'furnishing_status',
       'Mapped_Area', 'facing', 'property_age_bucket', 'is_ready_to_move',
       'is_built_up_area', 'is_carpet_area', 'is_super_built_up_area',
       'property_type', 'luxury_score', 'location_advantage_score'],
      dtype='str')

In [9]:
mask = df['property_type'].eq('other')

df.loc[mask & df['Name'].str.contains('plot', case=False, na=False), 'property_type'] = 'plot'

df.loc[mask & df['Name'].str.contains('flat|apartment', case=False, na=False), 'property_type'] = 'apartment'

df.loc[mask & df['Name'].str.contains('villa', case=False, na=False), 'property_type'] = 'villa'

df.loc[mask & df['Name'].str.contains('house', case=False, na=False), 'property_type'] = 'house'

df.loc[mask & df['Name'].str.contains('builder floor', case=False, na=False), 'property_type'] = 'builder floor'

df.loc[mask & df['Name'].str.contains('penthouse', case=False, na=False), 'property_type'] = 'penthouse'

df.loc[mask & df['Name'].str.contains('farmhouse', case=False, na=False), 'property_type'] = 'farmhouse'

In [10]:
mask = df['property_type'].isna()

df.loc[mask & df['Name'].str.contains('plot', case=False, na=False), 'property_type'] = 'plot'

df.loc[mask & df['Name'].str.contains('flat|apartment', case=False, na=False), 'property_type'] = 'apartment'

df.loc[mask & df['Name'].str.contains('villa', case=False, na=False), 'property_type'] = 'villa'

df.loc[mask & df['Name'].str.contains('house', case=False, na=False), 'property_type'] = 'house'

df.loc[mask & df['Name'].str.contains('builder floor', case=False, na=False), 'property_type'] = 'builder floor'

df.loc[mask & df['Name'].str.contains('penthouse', case=False, na=False), 'property_type'] = 'penthouse'

df.loc[mask & df['Name'].str.contains('farmhouse', case=False, na=False), 'property_type'] = 'farmhouse'

In [11]:
# df[df['property_type'] == 'other']['Name'].value_counts().head(50)
# df['property_type'].value_counts()

df[df['property_type'].isnull()][['Name','Price (INR in Lakhs)','Price_per_sqft','Area_sqft']]
# df[df['property_type'] == 'other'].head(10)

,Name,Price (INR in Lakhs),Price_per_sqft,Area_sqft
1751,"Residential propertyin Dahegam, Gandhinagar",6.0,3000.0,200.0
1752,"Residential propertyin Dahegam, Gandhinagar",8.0,36364.0,22.0
1876,"Residential propertyin Vavol, Gandhinagar",32.0,3200.0,1000.0

In [12]:
df.loc[1876, 'property_type'] = 'apartment'
df.drop([1751, 1752], inplace=True)  # commercial listings

In [13]:
df['property_type'].isnull().sum()

np.int64(0)

In [15]:
df[df['property_type'] == 'other'][['Name','Price (INR in Lakhs)','Price_per_sqft','Area_sqft','Property_URL','Description']]

,Name,Price (INR in Lakhs),Price_per_sqft,Area_sqft,Property_URL,Description
331,"Residential propertyin Mansa, Gandhinagar",27.0,2109.0,1280.000,https://www.99acres.com/other-residential-prop...,"Ready for immediate possession, this 1-5 year ..."
1174,"Residential propertyin Mansa, Gandhinagar",520.0,955.0,54455.076,https://www.99acres.com/other-residential-prop...,"Located in mansa, gandhinagar, this 54,450 sqf..."
1585,"Residential propertyin Kalol, Gandhinagar",50.0,16667.0,300.000,https://www.99acres.com/other-residential-prop...,"Situated in sneh residency, kalol, gandhinagar..."
1729,"Residential propertyin Lodra, Gandhinagar",250.0,319.0,78408.720,https://www.99acres.com/other-residential-prop...,"Located in lodra, gandhinagar, this brand-New ..."

In [16]:
# Manual verification from 99acres
df.loc[331, 'property_type'] = 'house'      # verified residential house
df.loc[1174, 'property_type'] = 'plot'      # verified residential plot
df.loc[1729, 'property_type'] = 'plot'      # verified large residential plot

# commercial property (shop)
df = df.drop(index=1585)

In [17]:
df['property_type'].value_counts()

property_type
apartment        1268
plot              130
house             121
villa             107
builder floor      36
penthouse          15
farmhouse           2
luxuryhouse         1
Name: count, dtype: int64

In [18]:
# Apartments
apartment_df = df[
    df['property_type'].isin(
        ['apartment', 'builder floor', 'penthouse']
    )
].copy()

# Houses & Villas
house_villa_df = df[
    df['property_type'].isin(
        ['house', 'villa', 'luxuryhouse']
    )
].copy()

# Plots
plot_df = df[
    df['property_type'].isin(
        ['plot', 'farmhouse']
    )
].copy()

In [19]:
print("Apartment:", apartment_df.shape)
print("House/Villa:", house_villa_df.shape)
print("Plot:", plot_df.shape)

Apartment: (1319, 23)
House/Villa: (229, 23)
Plot: (132, 23)

In [ ]:
apartment_df.to_csv("gandhinagar_property_apartments.csv", index=False)
house_villa_df.to_csv("gandhinagar_property_houses.csv", index=False)
plot_df.to_csv("gandhinagar_property_plots.csv", index=False)