In [75]:
from sklearn.pipeline import Pipeline
from sklearn.model_selection import cross_val_score, KFold, train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OrdinalEncoder, OneHotEncoder

from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import (
    RandomForestRegressor,
    ExtraTreesRegressor,
    GradientBoostingRegressor,
    AdaBoostRegressor
)
from sklearn.neural_network import MLPRegressor

from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from catboost import CatBoostRegressor

from category_encoders import TargetEncoder

import numpy as np
import pandas as pd

In [76]:
df=pd.read_csv('data//test.csv')

In [83]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1304 entries, 0 to 1303
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Price (INR in Lakhs)  1304 non-null   float64
 1   Area_sqft             1304 non-null   float64
 2   bathrooms             1304 non-null   float64
 3   balconies             1304 non-null   float64
 4   current_floor         1304 non-null   float64
 5   total_floors          1304 non-null   float64
 6   furnishing_status     1304 non-null   str
 7   Mapped_Area           1304 non-null   str
 8   facing                1304 non-null   str
 9   property_age_bucket   1304 non-null   str
 10  property_type         1304 non-null   str
 11  Bedrooms              1304 non-null   float64
 12  Area_type             1304 non-null   str
 13  Status                1304 non-null   str
dtypes: float64(7), str(7)
memory usage: 142.8 KB

In [ ]:
# df.drop(columns=['floor_ratio'], inplace=True)

In [22]:
df.rename(columns={'Price (INR in Lakhs)':'Price',
                   'Area_sqft':'Area',
                   'bathrooms':'Bathrooms',
                   'balconies':'Balconies',
                    'furnishing_status':'Furnishing_Status',
                    'facing':'Facing',
                    'property_age_bucket':'Property_Age',
                    'property_type':'Property_Type',
                    'Area_type':'Area_Type',
                    'Status':'Property_Status',
                    'current_floor':'Current_Floor',
                    'total_floors':'Total_Floor',
                    'luxury_category':'Luxury_Category',
                    'location_advantage_category':'Location_Advantage_Category',
                    'floor_category':'Floor_Category'
                    },inplace=True
          )

In [27]:
df['BHK']=df['BHK'].astype('category')
df['Mapped_Area']=df['Mapped_Area'].astype('category')
df['Location']=df['Location'].astype('category')
df['Furnishing_Status']=df['Furnishing_Status'].astype('category')
df['Facing']=df['Facing'].astype('category')
df['Property_Age']=df['Property_Age'].astype('category')
df['Area_Type']=df['Area_Type'].astype('category')
df['Property_Status']=df['Property_Status'].astype('category')
df['Property_Type']=df['Property_Type'].astype('category')
df['Floor_Category']=df['Floor_Category'].astype('category')
df['Luxury_Category']=df['Luxury_Category'].astype('category')
df['Location_Advantage_Category']=df['Location_Advantage_Category'].astype('category')

In [52]:
columns_to_encode=['Location','Property_Type','BHK','Mapped_Area','Furnishing_Status','Facing','Property_Age','Area_Type','Property_Status','Floor_Category','Luxury_Category','Location_Advantage_Category']

In [54]:
train_df=df

In [55]:
X=train_df.drop(columns=['Price'])
y=train_df['Price']
y_transformed=np.log1p(y)

In [56]:
X = train_df.drop(columns=['Price'])
y = train_df['Price']

# One-Hot Encoding
X_linear = pd.get_dummies(
    X,
    columns=columns_to_encode,
    drop_first=True,
    dtype=int
)

print(X_linear.shape)
X_linear.head()

(1304, 140)

,Area,Bathrooms,Balconies,Current_Floor,Total_Floor,Bedrooms,"Location_Adalaj, Gandhinagar","Location_Ambapur, Gandhinagar","Location_Ambika Nagar, Kalol, Gandhinagar","Location_Bhaijipura, Gandhinagar",...,Property_Status_Under_Construction,Floor_Category_Lower Floor,Floor_Category_Mid Floor,Floor_Category_Top Floor,Luxury_Category_Luxury,Luxury_Category_Premium,Luxury_Category_Unknown,Location_Advantage_Category_Excellent,Location_Advantage_Category_Good,Location_Advantage_Category_Unknown
0,2916.0,3.0,1.0,4.0,8.0,3.0,0,0,0,0,...,0,0,1,0,0,0,1,0,0,1
1,1755.0,3.0,2.0,3.0,7.0,3.0,0,0,0,0,...,1,0,1,0,0,0,1,0,0,1
2,1908.0,3.0,2.0,4.0,8.0,3.0,0,0,0,0,...,0,0,1,0,0,0,1,0,0,1
3,2205.0,2.0,2.0,9.0,13.0,3.0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,1
4,1755.0,3.0,1.0,8.0,13.0,3.0,0,0,0,0,...,0,0,1,0,0,0,1,0,0,0

In [57]:
pearson_corr = X_linear.corrwith(y).abs().sort_values(ascending=False)

pearson_df = pd.DataFrame({
    'Feature': pearson_corr.index,
    'Pearson': pearson_corr.values
})

pearson_df.head(20)

                               Feature   Pearson
0                                 Area  0.718954
1                             Bedrooms  0.656728
2                            Bathrooms  0.644726
3                            BHK_4 BHK  0.558837
4                          Total_Floor  0.465506
5   Property_Status_Under_Construction  0.385225
6                Mapped_Area_Gift City  0.368234
7      Location_Gift City, Gandhinagar  0.363169
8                            BHK_2 BHK  0.345584
9                        Current_Floor  0.316721
10                           BHK_6 BHK  0.278788
11                   Mapped_Area_Kalol  0.216717
12                           Balconies  0.206638
13            Area_Type_Super Built-up  0.204118
14                   Mapped_Area_Vavol  0.187767
15         Location_Kalol, Gandhinagar  0.186220
16         Location_Vavol, Gandhinagar  0.182815
17                    Area_Type_Carpet  0.170191
18                           BHK_3 BHK  0.168539
19             Property_Age_5-10 years  0.154793

In [58]:
spearman_corr = X_linear.corrwith(y, method='spearman').abs().sort_values(ascending=False)

spearman_df = pd.DataFrame({
    'Feature': spearman_corr.index,
    'Spearman': spearman_corr.values
})

spearman_df.head(20)

                               Feature  Spearman
0                             Bedrooms  0.705761
1                            Bathrooms  0.688490
2                                 Area  0.688397
3                          Total_Floor  0.545885
4                            BHK_2 BHK  0.449306
5                            BHK_3 BHK  0.436289
6                            BHK_4 BHK  0.397788
7                        Current_Floor  0.392137
8   Property_Status_Under_Construction  0.366509
9                Mapped_Area_Gift City  0.351224
10     Location_Gift City, Gandhinagar  0.348286
11                   Mapped_Area_Kalol  0.312169
12                   Mapped_Area_Vavol  0.275253
13         Location_Kalol, Gandhinagar  0.268934
14         Location_Vavol, Gandhinagar  0.267533
15            Area_Type_Super Built-up  0.214126
16             Property_Age_5-10 years  0.195768
17                           Balconies  0.195285
18                    Area_Type_Carpet  0.189175
19                    Property_Age_New  0.186383

In [59]:
from sklearn.feature_selection import mutual_info_regression

mi_scores = mutual_info_regression(
    X_linear,
    y,
    random_state=42
)

mi_df = pd.DataFrame({
    'Feature': X_linear.columns,
    'MI': mi_scores
}).sort_values('MI', ascending=False)

mi_df.head(20)

                                Feature        MI
0                                  Area  0.751344
5                              Bedrooms  0.560831
1                             Bathrooms  0.543480
4                           Total_Floor  0.314577
73                            BHK_2 BHK  0.298738
74                            BHK_3 BHK  0.267490
3                         Current_Floor  0.197391
75                            BHK_4 BHK  0.157470
130  Property_Status_Under_Construction  0.113188
83                Mapped_Area_Gift City  0.086392
84                    Mapped_Area_Kalol  0.082116
97                 Mapped_Area_Sargasan  0.071200
15      Location_Gift City, Gandhinagar  0.071016
18          Location_Kalol, Gandhinagar  0.058721
41       Location_Sargasan, Gandhinagar  0.056768
72                              BHK_1RK  0.056666
89                  Mapped_Area_Kudasan  0.054527
122                      Facing_Unknown  0.052071
132            Floor_Category_Mid Floor  0.049544
111                   Mapped_Area_Vavol  0.046655

In [60]:
from sklearn.feature_selection import f_regression

f_scores, p_values = f_regression(X_linear, y)

f_df = pd.DataFrame({
    'Feature': X_linear.columns,
    'F_Score': f_scores,
    'P_Value': p_values
}).sort_values('F_Score', ascending=False)

f_df.head(20)

                                Feature      F_Score        P_Value
0                                  Area  1393.065040  6.290831e-208
5                              Bedrooms   987.400548  9.111664e-162
1                             Bathrooms   926.201590  4.247106e-154
75                            BHK_4 BHK   591.265591  5.540797e-108
4                           Total_Floor   360.189917   4.208059e-71
130  Property_Status_Under_Construction   226.883614   2.192530e-47
83                Mapped_Area_Gift City   204.240672   3.791796e-43
15      Location_Gift City, Gandhinagar   197.812376   6.222789e-42
73                            BHK_2 BHK   176.584602   7.005902e-38
3                         Current_Floor   145.169016   9.008482e-32
77                            BHK_6 BHK   109.723331   1.047554e-24
84                    Mapped_Area_Kalol    64.163505   2.521453e-15
2                             Balconies    58.074070   4.838317e-14
129            Area_Type_Super Built-up    56.605090   9.894042e-14
111                   Mapped_Area_Vavol    47.581648   8.210070e-12
18          Location_Kalol, Gandhinagar    46.772672   1.222704e-11
64          Location_Vavol, Gandhinagar    45.019214   2.902704e-11
128                    Area_Type_Carpet    38.837219   6.209077e-10
74                            BHK_3 BHK    38.065271   9.117545e-10
125             Property_Age_5-10 years    31.963002   1.928871e-08

In [61]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LassoCV

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X_linear)

lasso = LassoCV(
    cv=5,
    random_state=42,
    max_iter=10000
)

lasso.fit(X_scaled, y)

lasso_df = pd.DataFrame({
    'Feature': X_linear.columns,
    'Lasso_Coeff': abs(lasso.coef_)
}).sort_values('Lasso_Coeff', ascending=False)

lasso_df.head(20)

                             Feature  Lasso_Coeff
0                               Area    25.245008
83             Mapped_Area_Gift City    13.006750
5                           Bedrooms    12.461082
75                         BHK_4 BHK     9.582989
15   Location_Gift City, Gandhinagar     7.294055
4                        Total_Floor     5.343639
77                         BHK_6 BHK     5.128156
45   Location_Sector 22, Gandhinagar     4.084022
50    Location_Sector 6, Gandhinagar     3.379211
1                          Bathrooms     2.892516
131       Floor_Category_Lower Floor     1.601480
94                Mapped_Area_Raysan     1.079279
38      Location_Raysan, Gandhinagar     0.366563
106             Mapped_Area_Sector 6     0.297034
117                Facing_North-West     0.198590
128                 Area_Type_Carpet     0.157445
105            Mapped_Area_Sector 29     0.084086
132         Floor_Category_Mid Floor     0.066805
98             Mapped_Area_Sector 11     0.021696
3                      Current_Floor     0.000000

In [62]:
rank_df = pd.DataFrame(index=X_linear.columns)

rank_df['Pearson'] = pearson_df.set_index('Feature')['Pearson'] \
                               .rank(ascending=False, method='average')

rank_df['Spearman'] = spearman_df.set_index('Feature')['Spearman'] \
                                 .rank(ascending=False, method='average')

rank_df['MI'] = mi_df.set_index('Feature')['MI'] \
                     .rank(ascending=False, method='average')

rank_df['F_Score'] = f_df.set_index('Feature')['F_Score'] \
                         .rank(ascending=False, method='average')

rank_df['Lasso'] = lasso_df.set_index('Feature')['Lasso_Coeff'] \
                           .rank(ascending=False, method='average')

In [63]:
rank_df['Average_Rank'] = rank_df.mean(axis=1)

final_linear_ranking = rank_df.sort_values('Average_Rank')

final_linear_ranking.head(60)

,Pearson,Spearman,MI,F_Score,Lasso,Average_Rank
Area,1.0,3.0,1.0,1.0,1.0,1.4
Bedrooms,2.0,1.0,2.0,2.0,3.0,2.0
Bathrooms,3.0,2.0,3.0,3.0,10.0,4.2
Total_Floor,5.0,4.0,4.0,5.0,6.0,4.8
BHK_4 BHK,4.0,7.0,8.0,4.0,4.0,5.4
Mapped_Area_Gift City,7.0,10.0,10.0,7.0,2.0,7.2
"Location_Gift City, Gandhinagar",8.0,11.0,13.0,8.0,5.0,9.0
BHK_2 BHK,9.0,5.0,5.0,9.0,80.0,21.6
Property_Status_Under_Construction,6.0,9.0,9.0,6.0,80.0,22.0
Current_Floor,10.0,8.0,7.0,10.0,80.0,23.0
Area_Type_Carpet,18.0,19.0,47.0,18.0,16.0,23.6
Mapped_Area_Kalol,12.0,12.0,11.0,12.0,80.0,25.4
BHK_3 BHK,19.0,6.0,6.0,19.0,80.0,26.0
Floor_Category_Lower Floor,25.0,49.0,24.0,25.0,11.0,26.8
Mapped_Area_Raysan,35.5,28.5,26.0,35.5,12.0,27.5
"Location_Kalol, Gandhinagar",16.0,14.0,14.0,16.0,80.0,28.0
Mapped_Area_Vavol,15.0,13.0,20.0,15.0,80.0,28.6
"Location_Raysan, Gandhinagar",35.5,28.5,33.0,35.5,13.0,29.1
Balconies,13.0,18.0,27.0,13.0,80.0,30.2
"Location_Vavol, Gandhinagar",17.0,15.0,25.0,17.0,80.0,30.8
Area_Type_Super Built-up,14.0,16.0,31.0,14.0,80.0,31.0
BHK_1RK,28.0,23.0,16.0,28.0,80.0,35.0
Property_Age_5-10 years,20.0,17.0,39.0,20.0,80.0,35.2
BHK_6 BHK,11.0,41.0,114.0,11.0,7.0,36.8
Facing_North-West,29.0,64.0,56.0,29.0,15.0,38.6
Mapped_Area_Pethapur,33.5,21.5,30.0,33.5,80.0,39.7
Luxury_Category_Unknown,27.0,25.0,41.0,27.0,80.0,40.0
Property_Age_New,26.0,20.0,51.0,26.0,80.0,40.6
Mapped_Area_Randheja,42.0,27.0,22.0,42.0,80.0,42.6
BHK_5 BHK,21.0,34.0,62.0,21.0,80.0,43.6
"Location_Pethapur, Gandhinagar",33.5,21.5,53.0,33.5,80.0,44.3
"Location_Koba, Gandhinagar",30.5,31.5,52.0,30.5,80.0,44.9
"Location_Randheja, Gandhinagar",41.0,26.0,38.0,41.0,80.0,45.2
Furnishing_Status_semi-furnished,40.0,33.0,37.0,40.0,80.0,46.0
Floor_Category_Mid Floor,44.0,105.0,19.0,44.0,18.0,46.0
Property_Age_10-20 years,32.0,24.0,65.0,32.0,80.0,46.6
Mapped_Area_Koba,30.5,31.5,74.0,30.5,80.0,49.3
"Location_Sargasan, Gandhinagar",37.0,86.0,15.0,37.0,80.0,51.0
Mapped_Area_Sargasan,38.0,94.0,12.0,38.0,80.0,52.4
Facing_Unknown,66.0,40.0,18.0,66.0,80.0,54.0
"Location_Sector 22, Gandhinagar",43.0,66.0,114.0,43.0,8.0,54.8
Facing_West,24.0,35.0,114.0,24.0,80.0,55.4
Mapped_Area_Kolavada,59.5,38.5,43.0,59.5,80.0,56.1
Mapped_Area_Khoraj,22.5,42.5,114.0,22.5,80.0,56.3
"Location_Khoraj, Gandhinagar",22.5,42.5,114.0,22.5,80.0,56.3
"Location_Urjanagar 1, Randesan, Gandhinagar",48.0,37.0,75.0,48.0,80.0,57.6
"Location_Chiloda, Gandhinagar",57.5,44.5,49.0,57.5,80.0,57.7
"Location_Sector 6, Gandhinagar",46.5,129.5,58.0,46.5,9.0,57.9
"Location_Dahegam, Gandhinagar",68.5,52.5,23.0,68.5,80.0,58.5
"Location_Randesan, Gandhinagar",71.0,30.0,44.0,71.0,80.0,59.2
Property_Type_builder floor,50.0,50.0,72.0,50.0,80.0,60.4
"Location_Kolavada, Gandhinagar",59.5,38.5,69.0,59.5,80.0,61.3
Floor_Category_Top Floor,63.0,58.0,48.0,63.0,80.0,62.4
Location_Advantage_Category_Unknown,56.0,77.0,46.0,56.0,80.0,63.0
Property_Type_penthouse,39.0,46.0,114.0,39.0,80.0,63.6
"Location_Ambapur, Gandhinagar",54.5,78.5,59.0,54.5,80.0,65.3
Mapped_Area_Ambapur,54.5,78.5,60.0,54.5,80.0,65.5
Facing_Other,52.0,63.0,85.0,52.0,80.0,66.4
Luxury_Category_Luxury,51.0,36.0,114.0,51.0,80.0,66.4
"Location_Ambika Nagar, Kalol, Gandhinagar",67.0,51.0,70.0,67.0,80.0,67.0

In [64]:
from sklearn.preprocessing import OrdinalEncoder

X = train_df.drop(columns=['Price'])
y = train_df['Price']

cat_cols = columns_to_encode

X_nonlinear = X.copy()

encoder = OrdinalEncoder(
    handle_unknown='use_encoded_value',
    unknown_value=-1
)

X_nonlinear[cat_cols] = encoder.fit_transform(X_nonlinear[cat_cols])

X_nonlinear.head()

,Location,Area,Bathrooms,Balconies,Current_Floor,Total_Floor,Furnishing_Status,Mapped_Area,Facing,Property_Age,Property_Type,Bedrooms,BHK,Area_Type,Property_Status,Luxury_Category,Location_Advantage_Category,Floor_Category
0,36.0,2916.0,3.0,1.0,4.0,8.0,0.0,19.0,8.0,3.0,0.0,3.0,3.0,2.0,0.0,3.0,3.0,2.0
1,26.0,1755.0,3.0,2.0,3.0,7.0,0.0,13.0,8.0,3.0,0.0,3.0,3.0,2.0,1.0,3.0,3.0,2.0
2,33.0,1908.0,3.0,2.0,4.0,8.0,0.0,16.0,8.0,3.0,0.0,3.0,3.0,2.0,0.0,3.0,3.0,2.0
3,33.0,2205.0,2.0,2.0,9.0,13.0,0.0,16.0,8.0,3.0,0.0,3.0,3.0,1.0,0.0,3.0,3.0,0.0
4,55.0,1755.0,3.0,1.0,8.0,13.0,3.0,14.0,8.0,2.0,0.0,3.0,3.0,1.0,0.0,3.0,0.0,2.0

In [65]:
from sklearn.ensemble import RandomForestRegressor
import pandas as pd

rf = RandomForestRegressor(
    n_estimators=500,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_nonlinear, y)

rf_df = pd.DataFrame({
    'Feature': X_nonlinear.columns,
    'RF_Importance': rf.feature_importances_
}).sort_values('RF_Importance', ascending=False)

rf_df.head(20)

                        Feature  RF_Importance
11                     Bedrooms       0.404262
1                          Area       0.218531
5                   Total_Floor       0.193911
12                          BHK       0.043060
4                 Current_Floor       0.029885
2                     Bathrooms       0.026413
7                   Mapped_Area       0.019142
0                      Location       0.018378
3                     Balconies       0.007730
9                  Property_Age       0.005856
8                        Facing       0.005717
13                    Area_Type       0.005697
15              Luxury_Category       0.004951
17               Floor_Category       0.004505
6             Furnishing_Status       0.003983
16  Location_Advantage_Category       0.003285
14              Property_Status       0.002753
10                Property_Type       0.001940

In [66]:
from sklearn.ensemble import ExtraTreesRegressor

et = ExtraTreesRegressor(
    n_estimators=500,
    random_state=42,
    n_jobs=-1
)

et.fit(X_nonlinear, y)

et_df = pd.DataFrame({
    'Feature': X_nonlinear.columns,
    'ET_Importance': et.feature_importances_
}).sort_values('ET_Importance', ascending=False)

et_df.head(20)

                        Feature  ET_Importance
11                     Bedrooms       0.206527
1                          Area       0.182163
5                   Total_Floor       0.141582
2                     Bathrooms       0.139687
12                          BHK       0.117015
14              Property_Status       0.042405
0                      Location       0.036098
7                   Mapped_Area       0.034699
4                 Current_Floor       0.025902
3                     Balconies       0.012470
17               Floor_Category       0.009936
13                    Area_Type       0.009588
8                        Facing       0.009095
9                  Property_Age       0.008850
6             Furnishing_Status       0.006960
15              Luxury_Category       0.006618
16  Location_Advantage_Category       0.005532
10                Property_Type       0.004874

In [67]:
from sklearn.ensemble import GradientBoostingRegressor

gbr = GradientBoostingRegressor(
    random_state=42
)

gbr.fit(X_nonlinear, y)

gbr_df = pd.DataFrame({
    'Feature': X_nonlinear.columns,
    'GBR_Importance': gbr.feature_importances_
}).sort_values('GBR_Importance', ascending=False)

gbr_df.head(20)

                        Feature  GBR_Importance
11                     Bedrooms        0.379378
1                          Area        0.292908
5                   Total_Floor        0.225926
4                 Current_Floor        0.022435
2                     Bathrooms        0.020694
0                      Location        0.017309
7                   Mapped_Area        0.016372
12                          BHK        0.009728
13                    Area_Type        0.003541
3                     Balconies        0.003068
6             Furnishing_Status        0.002169
15              Luxury_Category        0.002045
8                        Facing        0.001894
17               Floor_Category        0.001389
14              Property_Status        0.000666
9                  Property_Age        0.000320
16  Location_Advantage_Category        0.000159
10                Property_Type        0.000000

In [68]:
from sklearn.inspection import permutation_importance

perm = permutation_importance(
    rf,
    X_nonlinear,
    y,
    n_repeats=20,
    random_state=42,
    n_jobs=-1
)

perm_df = pd.DataFrame({
    'Feature': X_nonlinear.columns,
    'Permutation': perm.importances_mean
}).sort_values('Permutation', ascending=False)

perm_df.head(20)

                        Feature  Permutation
11                     Bedrooms     0.528887
1                          Area     0.521451
5                   Total_Floor     0.378306
2                     Bathrooms     0.036106
4                 Current_Floor     0.034893
7                   Mapped_Area     0.026926
12                          BHK     0.022435
0                      Location     0.021237
3                     Balconies     0.008052
13                    Area_Type     0.006900
9                  Property_Age     0.005518
8                        Facing     0.005241
15              Luxury_Category     0.004558
6             Furnishing_Status     0.004125
17               Floor_Category     0.003875
16  Location_Advantage_Category     0.003221
14              Property_Status     0.003093
10                Property_Type     0.001625

In [70]:
import shap
from sklearn.ensemble import RandomForestRegressor


rf = RandomForestRegressor(
    n_estimators=300,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_nonlinear, y)

explainer = shap.TreeExplainer(rf)
shap_values = explainer.shap_values(X_nonlinear)

shap_importance = np.abs(shap_values).mean(axis=0)

fi_shap = pd.DataFrame({
    'feature': X_nonlinear.columns,
    'shap_importance': shap_importance
}).sort_values(
    by='shap_importance',
    ascending=False
)

fi_shap

                        feature  shap_importance
11                     Bedrooms        19.217589
1                          Area        15.848135
5                   Total_Floor        14.107637
12                          BHK         2.423197
4                 Current_Floor         1.979401
7                   Mapped_Area         1.775204
2                     Bathrooms         1.712616
0                      Location         1.530848
15              Luxury_Category         0.533895
9                  Property_Age         0.510859
13                    Area_Type         0.487504
3                     Balconies         0.484775
17               Floor_Category         0.421258
8                        Facing         0.348863
14              Property_Status         0.334569
6             Furnishing_Status         0.317398
16  Location_Advantage_Category         0.220846
10                Property_Type         0.116070

In [71]:
from sklearn.feature_selection import RFE

rf = RandomForestRegressor(
    n_estimators=300,
    random_state=42,
    n_jobs=-1
)

# RFE
rfe = RFE(
    estimator=rf,
    n_features_to_select=1, 
    step=1
)

rfe.fit(X_nonlinear, y)


fi_rfe = pd.DataFrame({
    'feature': X_nonlinear.columns,
    'rfe_rank': rfe.ranking_
})

fi_rfe['rfe_score'] = 1 / fi_rfe['rfe_rank']

fi_rfe = fi_rfe.sort_values(
    by='rfe_rank',
    ascending=True
)

fi_rfe

                        feature  rfe_rank  rfe_score
1                          Area         1   1.000000
11                     Bedrooms         2   0.500000
5                   Total_Floor         3   0.333333
7                   Mapped_Area         4   0.250000
12                          BHK         5   0.200000
4                 Current_Floor         6   0.166667
2                     Bathrooms         7   0.142857
0                      Location         8   0.125000
3                     Balconies         9   0.111111
9                  Property_Age        10   0.100000
8                        Facing        11   0.090909
13                    Area_Type        12   0.083333
15              Luxury_Category        13   0.076923
17               Floor_Category        14   0.071429
6             Furnishing_Status        15   0.066667
16  Location_Advantage_Category        16   0.062500
14              Property_Status        17   0.058824
10                Property_Type        18   0.055556

In [69]:
from sklearn.feature_selection import mutual_info_regression

mi_scores = mutual_info_regression(
    X_nonlinear,
    y,
    random_state=42
)

mi_nonlinear_df = pd.DataFrame({
    'Feature': X_nonlinear.columns,
    'MI': mi_scores
}).sort_values('MI', ascending=False)

mi_nonlinear_df.head(20)

                        Feature        MI
1                          Area  0.761313
11                     Bedrooms  0.571144
12                          BHK  0.560880
2                     Bathrooms  0.519225
0                      Location  0.336458
7                   Mapped_Area  0.327335
5                   Total_Floor  0.281635
4                 Current_Floor  0.189813
14              Property_Status  0.093295
17               Floor_Category  0.088336
9                  Property_Age  0.071856
8                        Facing  0.039077
10                Property_Type  0.033881
16  Location_Advantage_Category  0.029440
13                    Area_Type  0.027692
15              Luxury_Category  0.027237
3                     Balconies  0.024697
6             Furnishing_Status  0.000000

In [72]:
nonlinear_df = pd.DataFrame({
    'feature': X_nonlinear.columns
})

nonlinear_df = nonlinear_df.merge(
    rf_df[['Feature','RF_Importance']],
    left_on='feature',
    right_on='Feature',
    how='left'
).drop(columns='Feature')

nonlinear_df = nonlinear_df.merge(
    et_df[['Feature','ET_Importance']],
    left_on='feature',
    right_on='Feature',
    how='left'
).drop(columns='Feature')

nonlinear_df = nonlinear_df.merge(
    gbr_df[['Feature','GBR_Importance']],
    left_on='feature',
    right_on='Feature',
    how='left'
).drop(columns='Feature')

nonlinear_df = nonlinear_df.merge(
    perm_df[['Feature','Permutation']],
    left_on='feature',
    right_on='Feature',
    how='left'
).drop(columns='Feature')

nonlinear_df = nonlinear_df.merge(
    fi_shap[['feature','shap_importance']],
    on='feature',
    how='left'
)

nonlinear_df = nonlinear_df.merge(
    fi_rfe[['feature','rfe_rank']],
    on='feature',
    how='left'
)

nonlinear_df.head()

,feature,RF_Importance,ET_Importance,GBR_Importance,Permutation,shap_importance,rfe_rank
0,Location,0.018378,0.036098,0.017309,0.021237,1.530848,8
1,Area,0.218531,0.182163,0.292908,0.521451,15.848135,1
2,Bathrooms,0.026413,0.139687,0.020694,0.036106,1.712616,7
3,Balconies,0.007730,0.012470,0.003068,0.008052,0.484775,9
4,Current_Floor,0.029885,0.025902,0.022435,0.034893,1.979401,6

In [73]:
rank_df = pd.DataFrame()

rank_df['feature'] = nonlinear_df['feature']

rank_df['RF_rank'] = nonlinear_df['RF_Importance'] \
                        .rank(ascending=False)

rank_df['ET_rank'] = nonlinear_df['ET_Importance'] \
                        .rank(ascending=False)

rank_df['GBR_rank'] = nonlinear_df['GBR_Importance'] \
                        .rank(ascending=False)

rank_df['Permutation_rank'] = nonlinear_df['Permutation'] \
                                .rank(ascending=False)

rank_df['SHAP_rank'] = nonlinear_df['shap_importance'] \
                            .rank(ascending=False)

rank_df['RFE_rank'] = nonlinear_df['rfe_rank']

In [74]:
rank_cols = [
    'RF_rank',
    'ET_rank',
    'GBR_rank',
    'Permutation_rank',
    'SHAP_rank',
    'RFE_rank'
]

rank_df['Average_Rank'] = rank_df[rank_cols].mean(axis=1)

final_nonlinear_ranking = rank_df.sort_values(
    'Average_Rank'
)

final_nonlinear_ranking

,feature,RF_rank,ET_rank,GBR_rank,Permutation_rank,SHAP_rank,RFE_rank,Average_Rank
11,Bedrooms,1.0,1.0,1.0,1.0,1.0,2,1.166667
1,Area,2.0,2.0,2.0,2.0,2.0,1,1.833333
5,Total_Floor,3.0,3.0,3.0,3.0,3.0,3,3.000000
2,Bathrooms,6.0,4.0,5.0,4.0,7.0,7,5.500000
12,BHK,4.0,5.0,8.0,7.0,4.0,5,5.500000
4,Current_Floor,5.0,9.0,4.0,5.0,5.0,6,5.666667
7,Mapped_Area,7.0,8.0,7.0,6.0,6.0,4,6.333333
0,Location,8.0,7.0,6.0,8.0,8.0,8,7.500000
3,Balconies,9.0,10.0,10.0,9.0,12.0,9,9.833333
13,Area_Type,12.0,12.0,9.0,10.0,11.0,12,11.000000
9,Property_Age,10.0,14.0,16.0,11.0,10.0,10,11.833333
8,Facing,11.0,13.0,13.0,12.0,14.0,11,12.333333
15,Luxury_Category,13.0,16.0,12.0,13.0,9.0,13,12.666667
17,Floor_Category,14.0,11.0,14.0,15.0,13.0,14,13.500000
6,Furnishing_Status,15.0,15.0,11.0,14.0,16.0,15,14.333333
14,Property_Status,17.0,6.0,15.0,17.0,15.0,17,14.500000
16,Location_Advantage_Category,16.0,17.0,17.0,16.0,17.0,16,16.500000
10,Property_Type,18.0,18.0,18.0,18.0,18.0,18,18.000000