In [ ]:
!pip install xgboost lightgbm catboost

Collecting xgboost
  Downloading xgboost-3.2.0-py3-none-win_amd64.whl.metadata (2.1 kB)
Collecting lightgbm
  Downloading lightgbm-4.6.0-py3-none-win_amd64.whl.metadata (17 kB)
Collecting catboost
  Downloading catboost-1.2.10-cp313-cp313-win_amd64.whl.metadata (1.5 kB)
Requirement already satisfied: numpy in c:\users\megh bavarva\desktop\data scientist\project\real_estate\code\venv\lib\site-packages (from xgboost) (2.4.6)
Requirement already satisfied: scipy in c:\users\megh bavarva\desktop\data scientist\project\real_estate\code\venv\lib\site-packages (from xgboost) (1.17.1)
Collecting graphviz (from catboost)
  Downloading graphviz-0.21-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: matplotlib in c:\users\megh bavarva\desktop\data scientist\project\real_estate\code\venv\lib\site-packages (from catboost) (3.10.9)
Requirement already satisfied: pandas<4.0,>=0.24 in c:\users\megh bavarva\desktop\data scientist\project\real_estate\code\venv\lib\site-packages (from catboost) (3.0.3)
Requirement already satisfied: plotly in c:\users\megh bavarva\desktop\data scientist\project\real_estate\code\venv\lib\site-packages (from catboost) (6.7.0)
Requirement already satisfied: six in c:\users\megh bavarva\desktop\data scientist\project\real_estate\code\venv\lib\site-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\megh bavarva\desktop\data scientist\project\real_estate\code\venv\lib\site-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\megh bavarva\desktop\data scientist\project\real_estate\code\venv\lib\site-packages (from pandas<4.0,>=0.24->catboost) (2026.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\megh bavarva\desktop\data scientist\project\real_estate\code\venv\lib\site-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\megh bavarva\desktop\data scientist\project\real_estate\code\venv\lib\site-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\megh bavarva\desktop\data scientist\project\real_estate\code\venv\lib\site-packages (from matplotlib->catboost) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\megh bavarva\desktop\data scientist\project\real_estate\code\venv\lib\site-packages (from matplotlib->catboost) (1.5.0)
Requirement already satisfied: packaging>=20.0 in c:\users\megh bavarva\desktop\data scientist\project\real_estate\code\venv\lib\site-packages (from matplotlib->catboost) (26.2)
Requirement already satisfied: pillow>=8 in c:\users\megh bavarva\desktop\data scientist\project\real_estate\code\venv\lib\site-packages (from matplotlib->catboost) (12.2.0)
Requirement already satisfied: pyparsing>=3 in c:\users\megh bavarva\desktop\data scientist\project\real_estate\code\venv\lib\site-packages (from matplotlib->catboost) (3.3.2)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\megh bavarva\desktop\data scientist\project\real_estate\code\venv\lib\site-packages (from plotly->catboost) (2.21.2)
Downloading xgboost-3.2.0-py3-none-win_amd64.whl (101.7 MB)
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/101.7 MB ? eta -:--:--
   ---------------------------------------- 0.5/101.7 MB 1.3 MB/s eta 0:01:19
   ---------------------------------------- 0.8/101.7 MB 1.4 MB/s eta 0:01:15
   ---------------------------------------- 0.8/101.7 MB 1.4 MB/s eta 0:01:15
    --------------------------------------- 1.3/101.7 MB 1.3 MB/s eta 0:01:18
    --------------------------------------- 1.6/101.7 MB 1.4 MB/s eta 0:01:13
    --------------------------------------- 1.8/101.7 MB 1.4 MB/s eta 0:01:14
    --------------------------------------- 2.1/101.7 MB 1.3 MB/s eta 0:01:17
   - -------------------------------------- 2.6/101.7 MB 1.4 MB/s eta 0:01:11
   - -------------------------------------- 2.9/101.7 MB 1.5 MB/s eta 0:01:09
   - -------------------------------------- 3.4/101.7 MB 1.5 MB/s eta 0:01:05
   - -------------------------------------- 3.9/101.7 MB 1.6 MB/s eta 0:01:01
   - -------------------------------------- 4.5/101.7 MB 1.7 MB/s eta 0:00:59
   - -------------------------------------- 4.7/101.7 MB 1.6 MB/s eta 0:01:00
   -- ------------------------------------- 5.2/101.7 MB 1.7 MB/s eta 0:00:57
   -- ------------------------------------- 5.5/101.7 MB 1.7 MB/s eta 0:00:58
   -- ------------------------------------- 5.8/101.7 MB 1.7 MB/s eta 0:00:57
   -- ------------------------------------- 6.0/101.7 MB 1.7 MB/s eta 0:00:57
   -- ------------------------------------- 6.6/101.7 MB 1.7 MB/s eta 0:00:57
   -- ------------------------------------- 7.1/101.7 MB 1.7 MB/s eta 0:00:56
   -- ------------------------------------- 7.6/101.7 MB 1.7 MB/s eta 0:00:55
   --- ------------------------------------ 8.1/101.7 MB 1.8 MB/s eta 0:00:53
   --- ------------------------------------ 8.7/101.7 MB 1.8 MB/s eta 0:00:52
   --- ------------------------------------ 9.2/101.7 MB 1.9 MB/s eta 0:00:51
   --- ------------------------------------ 10.0/101.7 MB 1.9 MB/s eta 0:00:49
   ---- ----------------------------------- 10.5/101.7 MB 1.9 MB/s eta 0:00:48
   ---- ----------------------------------- 11.0/101.7 MB 1.9 MB/s eta 0:00:47
   ---- ----------------------------------- 11.5/101.7 MB 2.0 MB/s eta 0:00:46
   ---- ----------------------------------- 12.3/101.7 MB 2.0 MB/s eta 0:00:45
   ----- ---------------------------------- 12.8/101.7 MB 2.0 MB/s eta 0:00:44
   ----- ---------------------------------- 13.4/101.7 MB 2.1 MB/s eta 0:00:43
   ----- ---------------------------------- 14.2/101.7 MB 2.1 MB/s eta 0:00:42
   ----- ---------------------------------- 14.4/101.7 MB 2.1 MB/s eta 0:00:43
   ----- ---------------------------------- 14.9/101.7 MB 2.1 MB/s eta 0:00:42
   ------ --------------------------------- 15.5/101.7 MB 2.1 MB/s eta 0:00:41
   ------ --------------------------------- 16.3/101.7 MB 2.1 MB/s eta 0:00:40
   ------ --------------------------------- 16.8/101.7 MB 2.1 MB/s eta 0:00:40
   ------ --------------------------------- 17.6/101.7 MB 2.2 MB/s eta 0:00:39
   ------- -------------------------------- 18.4/101.7 MB 2.2 MB/s eta 0:00:38
   ------- -------------------------------- 19.1/101.7 MB 2.3 MB/s eta 0:00:37
   ------- -------------------------------- 20.2/101.7 MB 2.3 MB/s eta 0:00:35
   -------- ------------------------------- 21.0/101.7 MB 2.4 MB/s eta 0:00:35
   -------- ------------------------------- 22.0/101.7 MB 2.4 MB/s eta 0:00:33
   -------- ------------------------------- 22.5/101.7 MB 2.4 MB/s eta 0:00:33
   --------- ------------------------------ 23.3/101.7 MB 2.5 MB/s eta 0:00:32
   --------- ------------------------------ 24.1/101.7 MB 2.5 MB/s eta 0:00:32
   --------- ------------------------------ 25.2/101.7 MB 2.5 MB/s eta 0:00:31
   ---------- ----------------------------- 26.2/101.7 MB 2.6 MB/s eta 0:00:30
   ---------- ----------------------------- 26.5/101.7 MB 2.6 MB/s eta 0:00:30
   ---------- ----------------------------- 27.3/101.7 MB 2.6 MB/s eta 0:00:29
   ----------- ---------------------------- 28.3/101.7 MB 2.6 MB/s eta 0:00:28
   ----------- ---------------------------- 29.6/101.7 MB 2.7 MB/s eta 0:00:27
   ----------- ---------------------------- 30.4/101.7 MB 2.7 MB/s eta 0:00:27
   ------------ --------------------------- 31.5/101.7 MB 2.8 MB/s eta 0:00:26
   ------------ --------------------------- 32.5/101.7 MB 2.8 MB/s eta 0:00:25
   ------------- -------------------------- 33.6/101.7 MB 2.8 MB/s eta 0:00:25
   ------------- -------------------------- 34.6/101.7 MB 2.9 MB/s eta 0:00:24
   -------------- ------------------------- 35.9/101.7 MB 2.9 MB/s eta 0:00:23
   -------------- ------------------------- 37.0/101.7 MB 3.0 MB/s eta 0:00:22
   -------------- ------------------------- 37.7/101.7 MB 3.0 MB/s eta 0:00:22
   --------------- ------------------------ 38.8/101.7 MB 3.0 MB/s eta 0:00:21
   --------------- ------------------------ 39.8/101.7 MB 3.0 MB/s eta 0:00:21
   ---------------- ----------------------- 40.9/101.7 MB 3.1 MB/s eta 0:00:20
   ---------------- ----------------------- 41.7/101.7 MB 3.1 MB/s eta 0:00:20
   ---------------- ----------------------- 42.7/101.7 MB 3.1 MB/s eta 0:00:19
   ---------------- ----------------------- 43.0/101.7 MB 3.1 MB/s eta 0:00:20
   ----------------- ---------------------- 44.8/101.7 MB 3.2 MB/s eta 0:00:19
   ------------------ --------------------- 45.9/101.7 MB 3.2 MB/s eta 0:00:18
   ------------------ --------------------- 46.7/101.7 MB 3.2 MB/s eta 0:00:18
   ------------------ --------------------- 48.0/101.7 MB 3.2 MB/s eta 0:00:17
   ------------------- -------------------- 49.0/101.7 MB 3.3 MB/s eta 0:00:17
   ------------------- -------------------- 50.1/101.7 MB 3.3 MB/s eta 0:00:16
   -------------------- ------------------- 50.9/101.7 MB 3.3 MB/s eta 0:00:16
   -------------------- ------------------- 52.2/101.7 MB 3.3 MB/s eta 0:00:15
   -------------------- ------------------- 53.2/101.7 MB 3.3 MB/s eta 0:00:15
   --------------------- ------------------ 54.5/101.7 MB 3.4 MB/s eta 0:00:14
   --------------------- ------------------ 55.6/101.7 MB 3.4 MB/s eta 0:00:14
   --------------------- ------------------ 55.8/101.7 MB 3.4 MB/s eta 0:00:14
   ---------------------- ----------------- 56.1/101.7 MB 3.4 MB/s eta 0:00:14
   ---------------------- ----------------- 57.4/101.7 MB 3.4 MB/s eta 0:00:14
   ---------------------- ----------------- 58.2/101.7 MB 3.4 MB/s eta 0:00:13
   ----------------------- ---------------- 59.0/101.7 MB 3.4 MB/s eta 0:00:13
   ----------------------- ---------------- 59.8/101.7 MB 3.4 MB/s eta 0:00:13
   ----------------------- ---------------- 60.6/101.7 MB 3.4 MB/s eta 0:00:13
   ------------------------ --------------- 61.1/101.7 MB 3.4 MB/s eta 0:00:12
   ------------------------ --------------- 62.1/101.7 MB 3.4 MB/s eta 0:00:12
   ------------------------ --------------- 62.9/101.7 MB 3.4 MB/s eta 0:00:12
   ------------------------- -------------- 63.7/101.7 MB 3.4 MB/s eta 0:00:12
   ------------------------- -------------- 64.2/101.7 MB 3.4 MB/s eta 0:00:11
   ------------------------- -------------- 65.3/101.7 MB 3.4 MB/s eta 0:00:11
   -------------------------- ------------- 66.6/101.7 MB 3.5 MB/s eta 0:00:11
   -------------------------- ------------- 66.8/101.7 MB 3.4 MB/s eta 0:00:11
   -------------------------- ------------- 67.4/101.7 MB 3.4 MB/s eta 0:00:11
   -------------------------- ------------- 68.2/101.7 MB 3.4 MB/s eta 0:00:10
   --------------------------- ------------ 69.2/101.7 MB 3.4 MB/s eta 0:00:10
   --------------------------- ------------ 70.3/101.7 MB 3.4 MB/s eta 0:00:10
   ---------------------------- ----------- 71.3/101.7 MB 3.5 MB/s eta 0:00:09
   ---------------------------- ----------- 72.4/101.7 MB 3.5 MB/s eta 0:00:09
   ---------------------------- ----------- 72.9/101.7 MB 3.5 MB/s eta 0:00:09
   ---------------------------- ----------- 73.7/101.7 MB 3.5 MB/s eta 0:00:09
   ----------------------------- ---------- 74.2/101.7 MB 3.5 MB/s eta 0:00:08
   ----------------------------- ---------- 74.7/101.7 MB 3.5 MB/s eta 0:00:08
   ----------------------------- ---------- 75.0/101.7 MB 3.4 MB/s eta 0:00:08
   ----------------------------- ---------- 75.8/101.7 MB 3.4 MB/s eta 0:00:08
   ------------------------------ --------- 76.3/101.7 MB 3.4 MB/s eta 0:00:08
   ------------------------------ --------- 77.3/101.7 MB 3.4 MB/s eta 0:00:08
   ------------------------------ --------- 78.1/101.7 MB 3.4 MB/s eta 0:00:07
   ------------------------------ --------- 78.6/101.7 MB 3.4 MB/s eta 0:00:07
   ------------------------------- -------- 79.2/101.7 MB 3.4 MB/s eta 0:00:07
   ------------------------------- -------- 79.7/101.7 MB 3.4 MB/s eta 0:00:07
   ------------------------------- -------- 80.2/101.7 MB 3.4 MB/s eta 0:00:07
   ------------------------------- -------- 80.7/101.7 MB 3.4 MB/s eta 0:00:07
   -------------------------------- ------- 81.5/101.7 MB 3.4 MB/s eta 0:00:06
   -------------------------------- ------- 82.6/101.7 MB 3.4 MB/s eta 0:00:06
   -------------------------------- ------- 83.1/101.7 MB 3.4 MB/s eta 0:00:06
   -------------------------------- ------- 83.9/101.7 MB 3.4 MB/s eta 0:00:06
   --------------------------------- ------ 84.9/101.7 MB 3.4 MB/s eta 0:00:05
   --------------------------------- ------ 85.5/101.7 MB 3.4 MB/s eta 0:00:05
   ---------------------------------- ----- 86.5/101.7 MB 3.4 MB/s eta 0:00:05
   ---------------------------------- ----- 87.6/101.7 MB 3.4 MB/s eta 0:00:05
   ---------------------------------- ----- 88.3/101.7 MB 3.4 MB/s eta 0:00:04
   ----------------------------------- ---- 89.1/101.7 MB 3.4 MB/s eta 0:00:04
   ----------------------------------- ---- 90.2/101.7 MB 3.4 MB/s eta 0:00:04
   ----------------------------------- ---- 90.7/101.7 MB 3.4 MB/s eta 0:00:04
   ----------------------------------- ---- 91.5/101.7 MB 3.4 MB/s eta 0:00:03
   ------------------------------------ --- 92.0/101.7 MB 3.4 MB/s eta 0:00:03
   ------------------------------------ --- 92.8/101.7 MB 3.4 MB/s eta 0:00:03
   ------------------------------------ --- 93.3/101.7 MB 3.4 MB/s eta 0:00:03
   ------------------------------------- -- 94.4/101.7 MB 3.4 MB/s eta 0:00:03
   ------------------------------------- -- 95.2/101.7 MB 3.4 MB/s eta 0:00:02
   ------------------------------------- -- 96.2/101.7 MB 3.5 MB/s eta 0:00:02
   -------------------------------------- - 97.0/101.7 MB 3.5 MB/s eta 0:00:02
   -------------------------------------- - 97.5/101.7 MB 3.5 MB/s eta 0:00:02
   -------------------------------------- - 98.6/101.7 MB 3.5 MB/s eta 0:00:01
   ---------------------------------------  99.6/101.7 MB 3.5 MB/s eta 0:00:01
   ---------------------------------------  100.4/101.7 MB 3.5 MB/s eta 0:00:01
   ---------------------------------------  101.2/101.7 MB 3.5 MB/s eta 0:00:01
   ---------------------------------------  101.4/101.7 MB 3.5 MB/s eta 0:00:01
   ---------------------------------------  101.4/101.7 MB 3.5 MB/s eta 0:00:01
   ---------------------------------------- 101.7/101.7 MB 3.4 MB/s eta 0:00:00
Downloading lightgbm-4.6.0-py3-none-win_amd64.whl (1.5 MB)
   ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
   --------------------- ------------------ 0.8/1.5 MB 4.7 MB/s eta 0:00:01
   ---------------------------------------- 1.5/1.5 MB 4.3 MB/s eta 0:00:00
Downloading catboost-1.2.10-cp313-cp313-win_amd64.whl (100.2 MB)
   ---------------------------------------- 0.0/100.2 MB ? eta -:--:--
   ---------------------------------------- 0.8/100.2 MB 4.2 MB/s eta 0:00:24
    --------------------------------------- 1.6/100.2 MB 4.2 MB/s eta 0:00:24
    --------------------------------------- 2.1/100.2 MB 4.3 MB/s eta 0:00:23
   - -------------------------------------- 3.1/100.2 MB 3.7 MB/s eta 0:00:27
   - -------------------------------------- 4.2/100.2 MB 4.0 MB/s eta 0:00:25
   - -------------------------------------- 4.5/100.2 MB 3.6 MB/s eta 0:00:27
   -- ------------------------------------- 5.2/100.2 MB 3.6 MB/s eta 0:00:27
   -- ------------------------------------- 6.3/100.2 MB 3.7 MB/s eta 0:00:26
   -- ------------------------------------- 7.1/100.2 MB 3.7 MB/s eta 0:00:25
   --- ------------------------------------ 8.1/100.2 MB 3.8 MB/s eta 0:00:25
   --- ------------------------------------ 8.9/100.2 MB 3.9 MB/s eta 0:00:24
   ---- ----------------------------------- 10.2/100.2 MB 4.0 MB/s eta 0:00:23
   ---- ----------------------------------- 11.3/100.2 MB 4.1 MB/s eta 0:00:22
   ---- ----------------------------------- 12.1/100.2 MB 4.1 MB/s eta 0:00:22
   ----- ---------------------------------- 13.4/100.2 MB 4.2 MB/s eta 0:00:21
   ----- ---------------------------------- 14.4/100.2 MB 4.2 MB/s eta 0:00:21
   ------ --------------------------------- 15.5/100.2 MB 4.3 MB/s eta 0:00:20
   ------ --------------------------------- 16.3/100.2 MB 4.3 MB/s eta 0:00:20
   ------ --------------------------------- 17.0/100.2 MB 4.2 MB/s eta 0:00:20
   ------- -------------------------------- 17.8/100.2 MB 4.2 MB/s eta 0:00:20
   ------- -------------------------------- 18.4/100.2 MB 4.1 MB/s eta 0:00:20
   ------- -------------------------------- 18.9/100.2 MB 4.1 MB/s eta 0:00:20
   ------- -------------------------------- 19.9/100.2 MB 4.1 MB/s eta 0:00:20
   -------- ------------------------------- 20.7/100.2 MB 4.1 MB/s eta 0:00:20
   -------- ------------------------------- 21.8/100.2 MB 4.1 MB/s eta 0:00:20
   --------- ------------------------------ 22.8/100.2 MB 4.1 MB/s eta 0:00:19
   --------- ------------------------------ 23.9/100.2 MB 4.2 MB/s eta 0:00:19
   --------- ------------------------------ 24.9/100.2 MB 4.2 MB/s eta 0:00:18
   ---------- ----------------------------- 26.2/100.2 MB 4.2 MB/s eta 0:00:18
   ---------- ----------------------------- 27.3/100.2 MB 4.3 MB/s eta 0:00:18
   ----------- ---------------------------- 28.3/100.2 MB 4.3 MB/s eta 0:00:17
   ----------- ---------------------------- 29.4/100.2 MB 4.3 MB/s eta 0:00:17
   ------------ --------------------------- 30.4/100.2 MB 4.3 MB/s eta 0:00:17
   ------------ --------------------------- 31.2/100.2 MB 4.3 MB/s eta 0:00:17
   ------------ --------------------------- 32.0/100.2 MB 4.3 MB/s eta 0:00:16
   ------------- -------------------------- 32.8/100.2 MB 4.3 MB/s eta 0:00:16
   ------------- -------------------------- 33.3/100.2 MB 4.2 MB/s eta 0:00:16
   ------------- -------------------------- 34.1/100.2 MB 4.2 MB/s eta 0:00:16
   -------------- ------------------------- 35.1/100.2 MB 4.2 MB/s eta 0:00:16
   -------------- ------------------------- 36.2/100.2 MB 4.2 MB/s eta 0:00:16
   -------------- ------------------------- 37.2/100.2 MB 4.2 MB/s eta 0:00:15
   --------------- ------------------------ 38.3/100.2 MB 4.3 MB/s eta 0:00:15
   --------------- ------------------------ 38.8/100.2 MB 4.2 MB/s eta 0:00:15
   --------------- ------------------------ 39.3/100.2 MB 4.2 MB/s eta 0:00:15
   ---------------- ----------------------- 40.4/100.2 MB 4.2 MB/s eta 0:00:15
   ---------------- ----------------------- 41.2/100.2 MB 4.2 MB/s eta 0:00:15
   ---------------- ----------------------- 42.2/100.2 MB 4.2 MB/s eta 0:00:14
   ----------------- ---------------------- 43.0/100.2 MB 4.2 MB/s eta 0:00:14
   ----------------- ---------------------- 43.5/100.2 MB 4.2 MB/s eta 0:00:14
   ----------------- ---------------------- 44.3/100.2 MB 4.2 MB/s eta 0:00:14
   ----------------- ---------------------- 44.8/100.2 MB 4.1 MB/s eta 0:00:14
   ------------------ --------------------- 45.6/100.2 MB 4.1 MB/s eta 0:00:14
   ------------------ --------------------- 46.4/100.2 MB 4.1 MB/s eta 0:00:14
   ------------------ --------------------- 47.4/100.2 MB 4.1 MB/s eta 0:00:13
   ------------------- -------------------- 48.2/100.2 MB 4.1 MB/s eta 0:00:13
   ------------------- -------------------- 49.0/100.2 MB 4.1 MB/s eta 0:00:13
   ------------------- -------------------- 49.8/100.2 MB 4.1 MB/s eta 0:00:13
   -------------------- ------------------- 50.9/100.2 MB 4.1 MB/s eta 0:00:13
   -------------------- ------------------- 51.6/100.2 MB 4.1 MB/s eta 0:00:12
   --------------------- ------------------ 53.0/100.2 MB 4.1 MB/s eta 0:00:12
   --------------------- ------------------ 53.7/100.2 MB 4.1 MB/s eta 0:00:12
   --------------------- ------------------ 54.8/100.2 MB 4.1 MB/s eta 0:00:11
   ---------------------- ----------------- 56.1/100.2 MB 4.2 MB/s eta 0:00:11
   ---------------------- ----------------- 56.9/100.2 MB 4.2 MB/s eta 0:00:11
   ----------------------- ---------------- 58.2/100.2 MB 4.2 MB/s eta 0:00:11
   ----------------------- ---------------- 58.7/100.2 MB 4.2 MB/s eta 0:00:10
   ----------------------- ---------------- 59.2/100.2 MB 4.2 MB/s eta 0:00:10

[notice] A new release of pip is available: 24.3.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.model_selection import cross_val_score, KFold, train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OrdinalEncoder, OneHotEncoder

from sklearn.linear_model import LinearRegression, Ridge, Lasso, ElasticNet
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import (
    RandomForestRegressor,
    ExtraTreesRegressor,
    GradientBoostingRegressor,
    AdaBoostRegressor
)
from sklearn.neural_network import MLPRegressor

from xgboost import XGBRegressor
from lightgbm import LGBMRegressor
from catboost import CatBoostRegressor

from category_encoders import TargetEncoder

import numpy as np
import pandas as pd

In [ ]:
df=pd.read_csv('data/gandhinagar_property_apartments_final.csv')
df.head()

,Price,Area,Bathrooms,Balconies,Current_Floor,Total_Floors,Furnishing_Status,Mapped_Area,Facing,Property_Age,Bedrooms,Area_Type,Property_Status
0,126.00,2916.0,3.0,1.0,4.0,8.0,Unknown,Sargasan,Unknown,New,3.0,Super Built-up,Ready_to_Move
1,51.99,1755.0,3.0,2.0,3.0,7.0,Unknown,Pethapur,Unknown,New,3.0,Super Built-up,Under_Construction
2,97.00,1908.0,3.0,2.0,4.0,8.0,Unknown,Raysan,Unknown,New,3.0,Super Built-up,Ready_to_Move
3,125.00,2205.0,2.0,2.0,9.0,13.0,Unknown,Raysan,Unknown,New,3.0,Carpet,Ready_to_Move
4,79.00,1755.0,3.0,1.0,8.0,13.0,unfurnished,Randesan,Unknown,5-10 years,3.0,Carpet,Ready_to_Move

In [49]:
X=df.drop(columns=['Price'])
y=df['Price']

In [50]:
y_transformed = np.log1p(y)

In [ ]:
def scorer(model_name, model):

    output = []

    pipeline = Pipeline([
        ('preprocessor', preprocessor),
        ('regressor', model)
    ])


    # Cross Validation R²
    kfold = KFold(
        n_splits=10,
        shuffle=True,
        random_state=42
    )

    cv_r2 = cross_val_score(
        pipeline,
        X,
        y_transformed,
        cv=kfold,
        scoring='r2'
    ).mean()

    # Train-Test Split
    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y_transformed,
        test_size=0.2,
        random_state=42
    )

    pipeline.fit(X_train, y_train)

    y_pred_log = pipeline.predict(X_test)

    # Test R² on log scale
    test_r2 = r2_score(y_test, y_pred_log)

    # Convert back to original scale
    y_test_original = np.expm1(y_test)
    y_pred_original = np.expm1(y_pred_log)

    mae = mean_absolute_error(
        y_test_original,
        y_pred_original
    )

    rmse = np.sqrt(
        mean_squared_error(
            y_test_original,
            y_pred_original
        )
    )

    output.extend([
        model_name,
        cv_r2,
        test_r2,
        mae,
        rmse
    ])

    return output

### Ordinal Encoding

In [73]:
columns_to_encode=['Mapped_Area','Furnishing_Status','Facing','Property_Age','Area_Type','Property_Status']

In [79]:
# Creating a column transformer for preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), ['Area', 'Bathrooms', 'Balconies', 'Current_Floor', 'Total_Floors', 'Bedrooms']),
        ('cat', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1), columns_to_encode)
    ], 
    remainder='passthrough'
)

In [92]:
model_dict = {

    # Linear Models
    'Linear Regression': LinearRegression(),
    'Ridge': Ridge(),
    'Lasso': Lasso(),
    'ElasticNet': ElasticNet(),

    # Support Vector
    'SVR': SVR(),

    # Tree Models
    'Decision Tree': DecisionTreeRegressor(random_state=42),
    'Random Forest': RandomForestRegressor(random_state=42),
    'Extra Trees': ExtraTreesRegressor(random_state=42),

    # Boosting
    'Gradient Boosting': GradientBoostingRegressor(random_state=42),
    'AdaBoost': AdaBoostRegressor(random_state=42),
    'XGBoost': XGBRegressor(
        random_state=42,
        verbosity=0
    ),
    'LightGBM': LGBMRegressor(
        random_state=42,
        verbose=-1
    ),
    'CatBoost': CatBoostRegressor(
        random_state=42,
        verbose=0
    ),

    # Neural Network
    'MLP': MLPRegressor(
        random_state=42,
        max_iter=1000
    )
}

In [93]:
model_output = []

for model_name, model in model_dict.items():
    model_output.append(
        scorer(model_name, model)
    )

c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

In [ ]:
model_df = pd.DataFrame(
    model_output,
    columns=[
        'Model',
        'CV_R2',
        'Test_R2',
        'MAE' ,
        'RMSE'
    ]
)

model_df.sort_values(
    by='MAE',
    ascending=True
).reset_index(drop=True)

                Model     CV_R2   Test_R2        MAE       RMSE
0         Extra Trees  0.835510  0.852689  15.477647  24.484725
1       Random Forest  0.840400  0.851957  15.829412  25.438885
2   Gradient Boosting  0.840182  0.845942  15.862121  25.605352
3            CatBoost  0.852181  0.844661  15.901018  25.933712
4            LightGBM  0.837811  0.842135  16.841208  27.691557
5             XGBoost  0.829533  0.824257  17.140123  27.792981
6                 SVR  0.797595  0.822018  17.456374  28.228738
7       Decision Tree  0.727436  0.735414  19.093607  32.973021
8               Ridge  0.727616  0.779277  20.941545  34.693636
9   Linear Regression  0.727573  0.779230  20.959509  34.738970
10                MLP  0.735689  0.690125  21.711843  38.855339
11           AdaBoost  0.713673  0.743770  23.223059  36.880803
12         ElasticNet  0.009744  0.015588  43.200015  70.789457
13              Lasso -0.010402 -0.010319  43.872745  71.497571

### One-Hot Encoding

In [104]:
# Creating a column transformer for preprocessing
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), ['Area', 'Bathrooms', 'Balconies', 'Current_Floor', 'Total_Floors', 'Bedrooms']),
        ('cat', OneHotEncoder(drop='first', handle_unknown='ignore'),
         ['Mapped_Area','Property_Age','Furnishing_Status','Area_Type','Property_Status','Facing'])
    ], 
    remainder='passthrough'
)

In [100]:
model_dict = {

    # Linear Models
    'Linear Regression': LinearRegression(),
    'Ridge': Ridge(),
    'Lasso': Lasso(),
    'ElasticNet': ElasticNet(),

    # Support Vector
    'SVR': SVR(),

    # Tree Models
    'Decision Tree': DecisionTreeRegressor(random_state=42),
    'Random Forest': RandomForestRegressor(random_state=42),
    'Extra Trees': ExtraTreesRegressor(random_state=42),

    # Boosting
    'Gradient Boosting': GradientBoostingRegressor(random_state=42),
    'AdaBoost': AdaBoostRegressor(random_state=42),
    'XGBoost': XGBRegressor(
        random_state=42,
        verbosity=0
    ),
    'LightGBM': LGBMRegressor(
        random_state=42,
        verbose=-1
    ),
    'CatBoost': CatBoostRegressor(
        random_state=42,
        verbose=0
    ),

    # Neural Network
    'MLP': MLPRegressor(
        random_state=42,
        max_iter=1000
    )
}

In [101]:
model_output = []

for model_name, model in model_dict.items():
    model_output.append(
        scorer(model_name, model)
    )

c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\preprocessing\_encoders.py:261: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros
  warnings.warn(msg, UserWarning)

In [102]:
model_df = pd.DataFrame(
    model_output,
    columns=[
        'Model',
        'CV_R2',
        'Test_R2',
        'MAE',
        'RMSE'
    ]
)

model_df.sort_values(
    by='MAE',
    ascending=True
).reset_index(drop=True)

                Model     CV_R2   Test_R2        MAE       RMSE
0         Extra Trees  0.841765  0.860881  15.303475  24.374174
1       Random Forest  0.856391  0.860709  15.476140  25.547307
2            CatBoost  0.861206  0.857527  15.621209  24.962270
3            LightGBM  0.847061  0.850237  16.456430  27.898937
4   Gradient Boosting  0.845305  0.848571  16.499305  27.273486
5                 SVR  0.850130  0.853114  16.638613  27.957609
6             XGBoost  0.849748  0.833963  16.887517  27.830439
7               Ridge  0.822849  0.845262  17.492583  28.061901
8   Linear Regression  0.812549  0.842769  17.624760  28.273033
9                 MLP  0.756537  0.758690  18.414111  28.487779
10      Decision Tree  0.779544  0.771716  18.650883  33.858303
11           AdaBoost  0.724828  0.715161  24.825061  39.001010
12              Lasso -0.010402 -0.010319  43.872745  71.497571
13         ElasticNet -0.010402 -0.010319  43.872745  71.497571

### Target Encoding

In [121]:
!pip install category_encoders

Collecting category_encoders
  Downloading category_encoders-2.9.0-py3-none-any.whl.metadata (7.9 kB)
Requirement already satisfied: numpy>=1.14.0 in c:\users\megh bavarva\desktop\data scientist\project\real_estate\code\venv\lib\site-packages (from category_encoders) (2.4.6)
Requirement already satisfied: pandas>=1.0.5 in c:\users\megh bavarva\desktop\data scientist\project\real_estate\code\venv\lib\site-packages (from category_encoders) (3.0.3)
Collecting patsy>=0.5.1 (from category_encoders)
  Downloading patsy-1.0.2-py2.py3-none-any.whl.metadata (3.6 kB)
Requirement already satisfied: scikit-learn>=1.6.0 in c:\users\megh bavarva\desktop\data scientist\project\real_estate\code\venv\lib\site-packages (from category_encoders) (1.8.0)
Requirement already satisfied: scipy>=1.0.0 in c:\users\megh bavarva\desktop\data scientist\project\real_estate\code\venv\lib\site-packages (from category_encoders) (1.17.1)
Collecting statsmodels>=0.9.0 (from category_encoders)
  Downloading statsmodels-0.14.6-cp313-cp313-win_amd64.whl.metadata (9.8 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\megh bavarva\desktop\data scientist\project\real_estate\code\venv\lib\site-packages (from pandas>=1.0.5->category_encoders) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\megh bavarva\desktop\data scientist\project\real_estate\code\venv\lib\site-packages (from pandas>=1.0.5->category_encoders) (2026.2)
Requirement already satisfied: joblib>=1.3.0 in c:\users\megh bavarva\desktop\data scientist\project\real_estate\code\venv\lib\site-packages (from scikit-learn>=1.6.0->category_encoders) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\megh bavarva\desktop\data scientist\project\real_estate\code\venv\lib\site-packages (from scikit-learn>=1.6.0->category_encoders) (3.6.0)
Requirement already satisfied: packaging>=21.3 in c:\users\megh bavarva\desktop\data scientist\project\real_estate\code\venv\lib\site-packages (from statsmodels>=0.9.0->category_encoders) (26.2)
Requirement already satisfied: six>=1.5 in c:\users\megh bavarva\desktop\data scientist\project\real_estate\code\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.0.5->category_encoders) (1.17.0)
Downloading category_encoders-2.9.0-py3-none-any.whl (85 kB)
Downloading patsy-1.0.2-py2.py3-none-any.whl (233 kB)
Downloading statsmodels-0.14.6-cp313-cp313-win_amd64.whl (9.5 MB)
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.5 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.5 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.5 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.5 MB 513.9 kB/s eta 0:00:18
   -- ------------------------------------- 0.5/9.5 MB 513.9 kB/s eta 0:00:18
   --- ------------------------------------ 0.8/9.5 MB 498.8 kB/s eta 0:00:18
   ---- ----------------------------------- 1.0/9.5 MB 647.4 kB/s eta 0:00:14
   ----- ---------------------------------- 1.3/9.5 MB 744.2 kB/s eta 0:00:12
   ----- ---------------------------------- 1.3/9.5 MB 744.2 kB/s eta 0:00:12
   ----- ---------------------------------- 1.3/9.5 MB 744.2 kB/s eta 0:00:12
   ----- ---------------------------------- 1.3/9.5 MB 744.2 kB/s eta 0:00:12
   ------ --------------------------------- 1.6/9.5 MB 610.8 kB/s eta 0:00:14
   ------ --------------------------------- 1.6/9.5 MB 610.8 kB/s eta 0:00:14
   ------- -------------------------------- 1.8/9.5 MB 586.3 kB/s eta 0:00:14
   -------- ------------------------------- 2.1/9.5 MB 653.7 kB/s eta 0:00:12
   --------- ------------------------------ 2.4/9.5 MB 664.1 kB/s eta 0:00:11
   --------- ------------------------------ 2.4/9.5 MB 664.1 kB/s eta 0:00:11
   ---------- ----------------------------- 2.6/9.5 MB 651.0 kB/s eta 0:00:11
   ---------- ----------------------------- 2.6/9.5 MB 651.0 kB/s eta 0:00:11
   ---------- ----------------------------- 2.6/9.5 MB 651.0 kB/s eta 0:00:11
   ------------ --------------------------- 2.9/9.5 MB 628.4 kB/s eta 0:00:11
   ------------ --------------------------- 2.9/9.5 MB 628.4 kB/s eta 0:00:11
   ------------ --------------------------- 2.9/9.5 MB 628.4 kB/s eta 0:00:11
   ------------- -------------------------- 3.1/9.5 MB 608.9 kB/s eta 0:00:11
   -------------- ------------------------- 3.4/9.5 MB 615.1 kB/s eta 0:00:10
   -------------- ------------------------- 3.4/9.5 MB 615.1 kB/s eta 0:00:10
   --------------- ------------------------ 3.7/9.5 MB 631.7 kB/s eta 0:00:10
   ---------------- ----------------------- 3.9/9.5 MB 644.7 kB/s eta 0:00:09
   ---------------- ----------------------- 3.9/9.5 MB 644.7 kB/s eta 0:00:09
   ----------------- ---------------------- 4.2/9.5 MB 648.0 kB/s eta 0:00:09
   ------------------ --------------------- 4.5/9.5 MB 658.3 kB/s eta 0:00:08
   ------------------- -------------------- 4.7/9.5 MB 674.8 kB/s eta 0:00:08
   --------------------- ------------------ 5.2/9.5 MB 734.2 kB/s eta 0:00:06
   ----------------------- ---------------- 5.5/9.5 MB 747.3 kB/s eta 0:00:06
   ------------------------ --------------- 5.8/9.5 MB 759.9 kB/s eta 0:00:05
   -------------------------- ------------- 6.3/9.5 MB 806.4 kB/s eta 0:00:05
   ---------------------------- ----------- 6.8/9.5 MB 851.9 kB/s eta 0:00:04
   ------------------------------ --------- 7.3/9.5 MB 895.2 kB/s eta 0:00:03
   -------------------------------- ------- 7.9/9.5 MB 930.5 kB/s eta 0:00:02
   ----------------------------------- ---- 8.4/9.5 MB 967.2 kB/s eta 0:00:02
   ------------------------------------ --- 8.7/9.5 MB 982.5 kB/s eta 0:00:01
   ---------------------------------------  9.4/9.5 MB 1.0 MB/s eta 0:00:01
   ---------------------------------------- 9.5/9.5 MB 1.0 MB/s eta 0:00:00
Installing collected packages: patsy, statsmodels, category_encoders
Successfully installed category_encoders-2.9.0 patsy-1.0.2 statsmodels-0.14.6

[notice] A new release of pip is available: 24.3.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [122]:
from category_encoders import TargetEncoder
from sklearn.pipeline import Pipeline

In [123]:
preprocessor = ColumnTransformer(
    transformers=[
        (
            'num',
            StandardScaler(),
            ['Area', 'Bathrooms', 'Balconies',
             'Current_Floor', 'Total_Floors', 'Bedrooms']
        ),
        (
            'cat',
            TargetEncoder(),
            ['Mapped_Area',
             'Property_Age',
             'Furnishing_Status',
             'Area_Type',
             'Property_Status',
             'Facing']
        )
    ]
)

In [125]:
model_dict = {

    # Linear Models
    'Linear Regression': LinearRegression(),
    'Ridge': Ridge(),
    'Lasso': Lasso(),
    'ElasticNet': ElasticNet(),

    # Support Vector
    'SVR': SVR(),

    # Tree Models
    'Decision Tree': DecisionTreeRegressor(random_state=42),
    'Random Forest': RandomForestRegressor(random_state=42),
    'Extra Trees': ExtraTreesRegressor(random_state=42),

    # Boosting
    'Gradient Boosting': GradientBoostingRegressor(random_state=42),
    'AdaBoost': AdaBoostRegressor(random_state=42),
    'XGBoost': XGBRegressor(
        random_state=42,
        verbosity=0
    ),
    'LightGBM': LGBMRegressor(
        random_state=42,
        verbose=-1
    ),
    'CatBoost': CatBoostRegressor(
        random_state=42,
        verbose=0
    ),

    # Neural Network
    'MLP': MLPRegressor(
        random_state=42,
        max_iter=1000
    )
}

In [126]:
model_output = []

for model_name, model in model_dict.items():
    model_output.append(
        scorer(model_name, model)
    )

c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

In [127]:
model_df = pd.DataFrame(
    model_output,
    columns=[
        'Model',
        'CV_R2',
        'Test_R2',
        'MAE',
        'RMSE'
    ]
)

model_df.sort_values(
    by='MAE',
    ascending=True
).reset_index(drop=True)

                Model     CV_R2   Test_R2        MAE       RMSE
0         Extra Trees  0.858939  0.874088  14.642607  23.009805
1       Random Forest  0.862527  0.871517  15.250700  25.404373
2            CatBoost  0.863833  0.865048  15.524284  24.140503
3   Gradient Boosting  0.849464  0.851613  15.747552  25.337459
4             XGBoost  0.848949  0.861840  15.859983  25.519415
5            LightGBM  0.850161  0.853851  16.753530  28.528900
6                 SVR  0.829232  0.838198  17.240262  28.887509
7       Decision Tree  0.776103  0.830688  17.326940  32.284660
8                 MLP  0.822867  0.838224  18.030593  31.518143
9               Ridge  0.808339  0.832104  18.106143  30.242917
10  Linear Regression  0.808200  0.831825  18.114719  30.275797
11           AdaBoost  0.734033  0.709197  26.233150  38.942399
12              Lasso -0.010402 -0.010319  43.872745  71.497571
13         ElasticNet -0.010402 -0.010319  43.872745  71.497571

In [ ]:
preprocessor = ColumnTransformer(
    transformers=[
        (
            'num',
            StandardScaler(),
            ['Area', 'Bathrooms', 'Balconies',
             'Current_Floor', 'Total_Floors', 'Bedrooms']
        ),
        (
            'target_enc',
            TargetEncoder(),
            ['Mapped_Area']
        ),
        (
            'ordinal_enc',
            OrdinalEncoder(
                handle_unknown='use_encoded_value',
                unknown_value=-1
            ),
            ['Property_Age',
             'Furnishing_Status',
             'Area_Type',
             'Property_Status',
             'Facing']
        )
    ],
    remainder='passthrough'
)

In [130]:
model_dict = {

    # Linear Models
    'Linear Regression': LinearRegression(),
    'Ridge': Ridge(),
    'Lasso': Lasso(),
    'ElasticNet': ElasticNet(),

    # Support Vector
    'SVR': SVR(),

    # Tree Models
    'Decision Tree': DecisionTreeRegressor(random_state=42),
    'Random Forest': RandomForestRegressor(random_state=42),
    'Extra Trees': ExtraTreesRegressor(random_state=42),

    # Boosting
    'Gradient Boosting': GradientBoostingRegressor(random_state=42),
    'AdaBoost': AdaBoostRegressor(random_state=42),
    'XGBoost': XGBRegressor(
        random_state=42,
        verbosity=0
    ),
    'LightGBM': LGBMRegressor(
        random_state=42,
        verbose=-1
    ),
    'CatBoost': CatBoostRegressor(
        random_state=42,
        verbose=0
    ),

    # Neural Network
    'MLP': MLPRegressor(
        random_state=42,
        max_iter=1000
    )
}

In [131]:
model_output = []

for model_name, model in model_dict.items():
    model_output.append(
        scorer(model_name, model)
    )

c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\MEGH BAVARVA\Desktop\Data Scientist\Project\Real_Estate\Code\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

In [132]:
model_df = pd.DataFrame(
    model_output,
    columns=[
        'Model',
        'CV_R2',
        'Test_R2',
        'MAE',
        'RMSE'
    ]
)

model_df.sort_values(
    by='MAE',
    ascending=True
).reset_index(drop=True)

                Model     CV_R2   Test_R2        MAE       RMSE
0         Extra Trees  0.858502  0.872602  14.795284  23.463178
1   Gradient Boosting  0.846240  0.854564  15.380796  24.305510
2       Random Forest  0.861249  0.866705  15.622391  25.816774
3            CatBoost  0.860615  0.858710  15.661591  24.633074
4             XGBoost  0.854449  0.856956  16.108233  26.042241
5                 SVR  0.833898  0.845392  16.130627  26.848576
6            LightGBM  0.852047  0.852430  16.733727  28.489689
7       Decision Tree  0.765311  0.834603  17.309027  33.181413
8                 MLP  0.801272  0.829069  17.326300  26.618388
9               Ridge  0.808431  0.834409  18.025936  29.911980
10  Linear Regression  0.808390  0.834169  18.043703  29.926894
11           AdaBoost  0.722248  0.698545  26.960033  39.743799
12              Lasso -0.010402 -0.010319  43.872745  71.497571
13         ElasticNet -0.010402 -0.010319  43.872745  71.497571

In [137]:
pip install hyperopt

[notice] A new release of pip is available: 24.3.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting hyperopt
  Downloading hyperopt-0.2.7-py2.py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: numpy in c:\users\megh bavarva\desktop\data scientist\project\real_estate\code\venv\lib\site-packages (from hyperopt) (2.4.6)
Requirement already satisfied: scipy in c:\users\megh bavarva\desktop\data scientist\project\real_estate\code\venv\lib\site-packages (from hyperopt) (1.17.1)
Requirement already satisfied: six in c:\users\megh bavarva\desktop\data scientist\project\real_estate\code\venv\lib\site-packages (from hyperopt) (1.17.0)
Collecting networkx>=2.2 (from hyperopt)
  Downloading networkx-3.6.1-py3-none-any.whl.metadata (6.8 kB)
Collecting future (from hyperopt)
  Downloading future-1.0.0-py3-none-any.whl.metadata (4.0 kB)
Requirement already satisfied: tqdm in c:\users\megh bavarva\desktop\data scientist\project\real_estate\code\venv\lib\site-packages (from hyperopt) (4.67.3)
Requirement already satisfied: cloudpickle in c:\users\megh bavarva\desktop\data scientist\project\real_estate\code\venv\lib\site-packages (from hyperopt) (3.1.2)
Collecting py4j (from hyperopt)
  Downloading py4j-0.10.9.9-py2.py3-none-any.whl.metadata (1.3 kB)
Requirement already satisfied: colorama in c:\users\megh bavarva\desktop\data scientist\project\real_estate\code\venv\lib\site-packages (from tqdm->hyperopt) (0.4.6)
Downloading hyperopt-0.2.7-py2.py3-none-any.whl (1.6 MB)
   ---------------------------------------- 0.0/1.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.6 MB ? eta -:--:--
   ------ --------------------------------- 0.3/1.6 MB ? eta -:--:--
   ------------- -------------------------- 0.5/1.6 MB 1.1 MB/s eta 0:00:01
   ------------------- -------------------- 0.8/1.6 MB 1.3 MB/s eta 0:00:01
   --------------------------------- ------ 1.3/1.6 MB 1.4 MB/s eta 0:00:01
   ---------------------------------------- 1.6/1.6 MB 1.5 MB/s eta 0:00:00
Downloading networkx-3.6.1-py3-none-any.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------- ----------------------------- 0.5/2.1 MB 3.9 MB/s eta 0:00:01
   ------------------------- -------------- 1.3/2.1 MB 3.5 MB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 3.6 MB/s eta 0:00:00
Downloading future-1.0.0-py3-none-any.whl (491 kB)
Downloading py4j-0.10.9.9-py2.py3-none-any.whl (203 kB)
Installing collected packages: py4j, networkx, future, hyperopt
Successfully installed future-1.0.0 hyperopt-0.2.7 networkx-3.6.1 py4j-0.10.9.9
Note: you may need to restart the kernel to use updated packages.

### Hyperparameter Tuning

In [141]:
from sklearn.ensemble import ExtraTreesRegressor
from sklearn.pipeline import Pipeline
from sklearn.model_selection import RandomizedSearchCV

In [142]:
preprocessor = ColumnTransformer(
    transformers=[
        (
            'num',
            StandardScaler(),
            ['Area', 'Bathrooms', 'Balconies',
             'Current_Floor', 'Total_Floors', 'Bedrooms']
        ),
        (
            'cat',
            TargetEncoder(),
            ['Mapped_Area',
             'Property_Age',
             'Furnishing_Status',
             'Area_Type',
             'Property_Status',
             'Facing']
        )
    ]
)

In [143]:
pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', ExtraTreesRegressor(random_state=42))
])

In [155]:
param_dist = {
    'regressor__n_estimators': [200, 300,400, 500, 750, 1000,1500],
    'regressor__max_depth': [None, 10, 20, 30, 40,50],
    'regressor__min_samples_split': [2, 5, 10,15,20],
    'regressor__min_samples_leaf': [1, 2, 4,8],
    'regressor__max_features': ['sqrt', 'log2', None]
}

In [156]:
random_search = RandomizedSearchCV(
    estimator=pipeline,
    param_distributions=param_dist,
    n_iter=200,                
    cv=5,
    scoring='neg_mean_absolute_error',
    n_jobs=-1,
    random_state=42,
    verbose=2
)

In [157]:
random_search.fit(X, y_transformed)

Fitting 5 folds for each of 200 candidates, totalling 1000 fits

RandomizedSearchCV(cv=5,
                   estimator=Pipeline(steps=[('preprocessor',
                                              ColumnTransformer(transformers=[('num',
                                                                               StandardScaler(),
                                                                               ['Area',
                                                                                'Bathrooms',
                                                                                'Balconies',
                                                                                'Current_Floor',
                                                                                'Total_Floors',
                                                                                'Bedrooms']),
                                                                              ('cat',
                                                                               TargetEncoder(),
                                                                               ['Mapped_Area',
                                                                                'Property_Age',
                                                                                'Furnishing_Status',
                                                                                'Area_Type',
                                                                                'Property_Status',
                                                                                'Facing'])])),
                                             ('regressor',
                                              ExtraTreesRegressor(ra...ate=42))]),
                   n_iter=200, n_jobs=-1,
                   param_distributions={'regressor__max_depth': [None, 10, 20,
                                                                 30, 40, 50],
                                        'regressor__max_features': ['sqrt',
                                                                    'log2',
                                                                    None],
                                        'regressor__min_samples_leaf': [1, 2, 4,
                                                                        8],
                                        'regressor__min_samples_split': [2, 5,
                                                                         10, 15,
                                                                         20],
                                        'regressor__n_estimators': [200, 300,
                                                                    400, 500,
                                                                    750, 1000,
                                                                    1500]},
                   random_state=42, scoring='neg_mean_absolute_error',
                   verbose=2)

In [158]:
print("Best Parameters:")
print(random_search.best_params_)

print("\nBest CV MAE:")
print(-random_search.best_score_)

Best Parameters:
{'regressor__n_estimators': 1500, 'regressor__min_samples_split': 5, 'regressor__min_samples_leaf': 2, 'regressor__max_features': None, 'regressor__max_depth': 50}

Best CV MAE:
0.15815866606732495

In [159]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
import numpy as np

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y_transformed,
    test_size=0.3,
    random_state=42
)

best_model = random_search.best_estimator_

best_model.fit(X_train, y_train)

y_pred_log = best_model.predict(X_test)

r2 = r2_score(y_test, y_pred_log)

# Back to original price scale
y_test_actual = np.expm1(y_test)
y_pred_actual = np.expm1(y_pred_log)

mae = mean_absolute_error(y_test_actual, y_pred_actual)

rmse = np.sqrt(
    mean_squared_error(y_test_actual, y_pred_actual)
)

print(f"R² Score : {r2:.4f}")
print(f"MAE      : {mae:.4f}")
print(f"RMSE     : {rmse:.4f}")

R² Score : 0.8767
MAE      : 14.8610
RMSE     : 26.8479

regressor_n_estimators = 300
regressor_max_depth = 20
regressor_min_samples_split = 5
regressor_min_samples_leaf = 2
regressor__max_features = 'None'
MAE : 0.1579 

R2 score :0.8777
MAE:14.78
RMSE: 26.58

In [161]:
param_dist = {
    'regressor__n_estimators': [200, 250, 300, 350, 400, 450],
    'regressor__max_depth': [15, 18, 20, 22, 25],
    'regressor__min_samples_split': [2, 3, 4, 5, 6, 7, 8],
    'regressor__min_samples_leaf': [1, 2, 3, 4],
    'regressor__max_features': [None]
}

In [162]:
from sklearn.model_selection import GridSearchCV

grid_search = GridSearchCV(
    estimator=pipeline,
    param_grid=param_dist,
    cv=5,
    scoring='neg_mean_absolute_error',
    n_jobs=-1,
    verbose=2
)

grid_search.fit(X, y_transformed)

Fitting 5 folds for each of 840 candidates, totalling 4200 fits

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(transformers=[('num',
                                                                         StandardScaler(),
                                                                         ['Area',
                                                                          'Bathrooms',
                                                                          'Balconies',
                                                                          'Current_Floor',
                                                                          'Total_Floors',
                                                                          'Bedrooms']),
                                                                        ('cat',
                                                                         TargetEncoder(),
                                                                         ['Mapped_Area',
                                                                          'Property_Age',
                                                                          'Furnishing_Status',
                                                                          'Area_Type',
                                                                          'Property_Status',
                                                                          'Facing'])])),
                                       ('regressor',
                                        ExtraTreesRegressor(random_state=42))]),
             n_jobs=-1,
             param_grid={'regressor__max_depth': [15, 18, 20, 22, 25],
                         'regressor__max_features': [None],
                         'regressor__min_samples_leaf': [1, 2, 3, 4],
                         'regressor__min_samples_split': [2, 3, 4, 5, 6, 7, 8],
                         'regressor__n_estimators': [200, 250, 300, 350, 400,
                                                     450]},
             scoring='neg_mean_absolute_error', verbose=2)

In [163]:
print("Best Parameters:")
print(grid_search.best_params_)

print("\nBest CV MAE:")
print(-grid_search.best_score_)

Best Parameters:
{'regressor__max_depth': 25, 'regressor__max_features': None, 'regressor__min_samples_leaf': 1, 'regressor__min_samples_split': 7, 'regressor__n_estimators': 350}

Best CV MAE:
0.1576183729080363

In [164]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
import numpy as np

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y_transformed,
    test_size=0.3,
    random_state=42
)

best_model = grid_search.best_estimator_

best_model.fit(X_train, y_train)

y_pred_log = best_model.predict(X_test)

r2 = r2_score(y_test, y_pred_log)

# Back to original price scale
y_test_actual = np.expm1(y_test)
y_pred_actual = np.expm1(y_pred_log)

mae = mean_absolute_error(y_test_actual, y_pred_actual)

rmse = np.sqrt(
    mean_squared_error(y_test_actual, y_pred_actual)
)

print(f"R² Score : {r2:.4f}")
print(f"MAE      : {mae:.4f}")
print(f"RMSE     : {rmse:.4f}")

R² Score : 0.8791
MAE      : 14.4203
RMSE     : 25.6870

In [170]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.pipeline import Pipeline

In [171]:
preprocessor = ColumnTransformer(
    transformers=[
        (
            'num',
            StandardScaler(),
            ['Area', 'Bathrooms', 'Balconies',
             'Current_Floor', 'Total_Floors', 'Bedrooms']
        ),
        (
            'cat',
            TargetEncoder(),
            ['Mapped_Area',
             'Property_Age',
             'Furnishing_Status',
             'Area_Type',
             'Property_Status',
             'Facing']
        )
    ]
)

In [172]:
pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', RandomForestRegressor(random_state=42))
])

In [173]:
param_dist = {
    'regressor__n_estimators': [200, 300, 500, 750, 1000],
    'regressor__max_depth': [None, 10, 20, 30, 40],
    'regressor__min_samples_split': [2, 5, 10],
    'regressor__min_samples_leaf': [1, 2, 4],
    'regressor__max_features': ['sqrt', 'log2', None],
    'regressor__bootstrap': [True, False]
}

In [174]:
from sklearn.model_selection import RandomizedSearchCV

random_search = RandomizedSearchCV(
    estimator=pipeline,
    param_distributions=param_dist,
    n_iter=200,
    cv=5,
    scoring='neg_mean_absolute_error',
    n_jobs=-1,
    random_state=42,
    verbose=2
)

random_search.fit(X, y_transformed)

Fitting 5 folds for each of 200 candidates, totalling 1000 fits

RandomizedSearchCV(cv=5,
                   estimator=Pipeline(steps=[('preprocessor',
                                              ColumnTransformer(transformers=[('num',
                                                                               StandardScaler(),
                                                                               ['Area',
                                                                                'Bathrooms',
                                                                                'Balconies',
                                                                                'Current_Floor',
                                                                                'Total_Floors',
                                                                                'Bedrooms']),
                                                                              ('cat',
                                                                               TargetEncoder(),
                                                                               ['Mapped_Area',
                                                                                'Property_Age',
                                                                                'Furnishing_Status',
                                                                                'Area_Type',
                                                                                'Property_Status',
                                                                                'Facing'])])),
                                             ('regressor',
                                              RandomForestRegressor(...
                   n_iter=200, n_jobs=-1,
                   param_distributions={'regressor__bootstrap': [True, False],
                                        'regressor__max_depth': [None, 10, 20,
                                                                 30, 40],
                                        'regressor__max_features': ['sqrt',
                                                                    'log2',
                                                                    None],
                                        'regressor__min_samples_leaf': [1, 2,
                                                                        4],
                                        'regressor__min_samples_split': [2, 5,
                                                                         10],
                                        'regressor__n_estimators': [200, 300,
                                                                    500, 750,
                                                                    1000]},
                   random_state=42, scoring='neg_mean_absolute_error',
                   verbose=2)

In [175]:
print("Best Parameters:")
print(random_search.best_params_)

print("\nBest CV MAE:")
print(-random_search.best_score_)

Best Parameters:
{'regressor__n_estimators': 200, 'regressor__min_samples_split': 5, 'regressor__min_samples_leaf': 2, 'regressor__max_features': 'sqrt', 'regressor__max_depth': 20, 'regressor__bootstrap': False}

Best CV MAE:
0.15727290674224662

In [176]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
import numpy as np

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y_transformed,
    test_size=0.2,
    random_state=42
)

best_model = random_search.best_estimator_

best_model.fit(X_train, y_train)

y_pred_log = best_model.predict(X_test)

r2 = r2_score(y_test, y_pred_log)

y_test_actual = np.expm1(y_test)
y_pred_actual = np.expm1(y_pred_log)

mae = mean_absolute_error(y_test_actual, y_pred_actual)

rmse = np.sqrt(mean_squared_error(y_test_actual, y_pred_actual))

print(f"R² Score : {r2:.4f}")
print(f"MAE      : {mae:.4f}")
print(f"RMSE     : {rmse:.4f}")

R² Score : 0.8755
MAE      : 15.3039
RMSE     : 25.8979

In [177]:
param_dist = {
    'regressor__n_estimators': [100, 150, 200, 250, 300, 350],
    'regressor__max_depth': [15, 18, 20, 22, 25, 30],
    'regressor__min_samples_split': [3, 4, 5, 6, 7],
    'regressor__min_samples_leaf': [1, 2, 3],
    'regressor__max_features': ['sqrt'],
    'regressor__bootstrap': [False]
}

In [178]:
from sklearn.model_selection import GridSearchCV

param_grid = {
    'regressor__n_estimators': [150, 200, 250, 300],
    'regressor__max_depth': [18, 20, 22, 25],
    'regressor__min_samples_split': [4, 5, 6],
    'regressor__min_samples_leaf': [1, 2, 3],
    'regressor__max_features': ['sqrt'],
    'regressor__bootstrap': [False]
}

grid_search = GridSearchCV(
    estimator=pipeline,
    param_grid=param_grid,
    cv=5,
    scoring='neg_mean_absolute_error',
    n_jobs=-1,
    verbose=2
)

grid_search.fit(X, y_transformed)

Fitting 5 folds for each of 144 candidates, totalling 720 fits

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(transformers=[('num',
                                                                         StandardScaler(),
                                                                         ['Area',
                                                                          'Bathrooms',
                                                                          'Balconies',
                                                                          'Current_Floor',
                                                                          'Total_Floors',
                                                                          'Bedrooms']),
                                                                        ('cat',
                                                                         TargetEncoder(),
                                                                         ['Mapped_Area',
                                                                          'Property_Age',
                                                                          'Furnishing_Status',
                                                                          'Area_Type',
                                                                          'Property_Status',
                                                                          'Facing'])])),
                                       ('regressor',
                                        RandomForestRegressor(random_state=42))]),
             n_jobs=-1,
             param_grid={'regressor__bootstrap': [False],
                         'regressor__max_depth': [18, 20, 22, 25],
                         'regressor__max_features': ['sqrt'],
                         'regressor__min_samples_leaf': [1, 2, 3],
                         'regressor__min_samples_split': [4, 5, 6],
                         'regressor__n_estimators': [150, 200, 250, 300]},
             scoring='neg_mean_absolute_error', verbose=2)

In [179]:
print("Best Parameters:")
print(grid_search.best_params_)

print("\nBest CV MAE:")
print(-grid_search.best_score_)

Best Parameters:
{'regressor__bootstrap': False, 'regressor__max_depth': 25, 'regressor__max_features': 'sqrt', 'regressor__min_samples_leaf': 1, 'regressor__min_samples_split': 6, 'regressor__n_estimators': 150}

Best CV MAE:
0.15663232813631006

In [180]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
import numpy as np

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y_transformed,
    test_size=0.2,
    random_state=42
)

best_model = grid_search.best_estimator_

best_model.fit(X_train, y_train)

y_pred_log = best_model.predict(X_test)

r2 = r2_score(y_test, y_pred_log)

y_test_actual = np.expm1(y_test)
y_pred_actual = np.expm1(y_pred_log)

mae = mean_absolute_error(y_test_actual, y_pred_actual)

rmse = np.sqrt(mean_squared_error(y_test_actual, y_pred_actual))

print(f"R² Score : {r2:.4f}")
print(f"MAE      : {mae:.4f}")
print(f"RMSE     : {rmse:.4f}")

R² Score : 0.8782
MAE      : 15.1647
RMSE     : 25.4775

In [2]:
pip install hyperopt==0.2.7

Requirement already satisfied: hyperopt==0.2.7 in c:\users\megh bavarva\desktop\data scientist\project\real_estate\code\venv\lib\site-packages (0.2.7)
Requirement already satisfied: numpy in c:\users\megh bavarva\desktop\data scientist\project\real_estate\code\venv\lib\site-packages (from hyperopt==0.2.7) (2.4.6)
Requirement already satisfied: scipy in c:\users\megh bavarva\desktop\data scientist\project\real_estate\code\venv\lib\site-packages (from hyperopt==0.2.7) (1.17.1)
Requirement already satisfied: six in c:\users\megh bavarva\desktop\data scientist\project\real_estate\code\venv\lib\site-packages (from hyperopt==0.2.7) (1.17.0)
Requirement already satisfied: networkx>=2.2 in c:\users\megh bavarva\desktop\data scientist\project\real_estate\code\venv\lib\site-packages (from hyperopt==0.2.7) (3.6.1)
Requirement already satisfied: future in c:\users\megh bavarva\desktop\data scientist\project\real_estate\code\venv\lib\site-packages (from hyperopt==0.2.7) (1.0.0)
Requirement already satisfied: tqdm in c:\users\megh bavarva\desktop\data scientist\project\real_estate\code\venv\lib\site-packages (from hyperopt==0.2.7) (4.67.3)
Requirement already satisfied: cloudpickle in c:\users\megh bavarva\desktop\data scientist\project\real_estate\code\venv\lib\site-packages (from hyperopt==0.2.7) (3.1.2)
Requirement already satisfied: py4j in c:\users\megh bavarva\desktop\data scientist\project\real_estate\code\venv\lib\site-packages (from hyperopt==0.2.7) (0.10.9.9)
Requirement already satisfied: colorama in c:\users\megh bavarva\desktop\data scientist\project\real_estate\code\venv\lib\site-packages (from tqdm->hyperopt==0.2.7) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [6]:
from hyperopt import hp

In [7]:
space = {
    'iterations': hp.quniform('iterations', 300, 1500, 100),
    'depth': hp.quniform('depth', 4, 10, 1),
    'learning_rate': hp.loguniform('learning_rate', -5, -1),
    'l2_leaf_reg': hp.uniform('l2_leaf_reg', 1, 15),
    'subsample': hp.uniform('subsample', 0.6, 1.0)
}

In [8]:
from hyperopt import STATUS_OK
from sklearn.model_selection import cross_val_score, KFold
from catboost import CatBoostRegressor
from sklearn.pipeline import Pipeline

def objective(params):

    model = CatBoostRegressor(
        iterations=int(params['iterations']),
        depth=int(params['depth']),
        learning_rate=params['learning_rate'],
        l2_leaf_reg=params['l2_leaf_reg'],
        subsample=params['subsample'],
        random_state=42,
        verbose=0
    )

    pipeline = Pipeline([
        ('preprocessor', preprocessor),
        ('regressor', model)
    ])

    cv = KFold(
        n_splits=5,
        shuffle=True,
        random_state=42
    )

    score = cross_val_score(
        pipeline,
        X,
        y_transformed,
        cv=cv,
        scoring='neg_mean_absolute_error',
        n_jobs=-1
    ).mean()

    return {
        'loss': -score,
        'status': STATUS_OK
    }

In [23]:
preprocessor = ColumnTransformer(
    transformers=[
        (
            'num',
            StandardScaler(),
            ['Area', 'Bathrooms', 'Balconies',
             'Current_Floor', 'Total_Floors', 'Bedrooms']
        ),
        (
            'cat',
            TargetEncoder(),
            ['Mapped_Area',
             'Property_Age',
             'Furnishing_Status',
             'Area_Type',
             'Property_Status',
             'Facing']
        )
    ]
)

In [24]:
from hyperopt import fmin, tpe, Trials
import numpy as np

trials = Trials()

best = fmin(
    fn=objective,
    space=space,
    algo=tpe.suggest,
    max_evals=100,
    trials=trials,
    rstate=np.random.default_rng(42)
)

print(best)

100%|██████████| 100/100 [04:22<00:00,  2.63s/trial, best loss: 0.14474575557422426]
{'depth': np.float64(6.0), 'iterations': np.float64(1100.0), 'l2_leaf_reg': np.float64(1.9622562392303726), 'learning_rate': np.float64(0.02336501505908804), 'subsample': np.float64(0.7523264831222428)}

In [25]:
from catboost import CatBoostRegressor

final_cat = CatBoostRegressor(
    iterations=int(best['iterations']),
    depth=int(best['depth']),
    learning_rate=best['learning_rate'],
    l2_leaf_reg=best['l2_leaf_reg'],
    subsample=best['subsample'],
    random_state=42,
    verbose=0
)

In [26]:
from sklearn.pipeline import Pipeline

pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', final_cat)
])

In [27]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y_transformed,
    test_size=0.2,
    random_state=42
)

In [28]:
pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['Area', 'Bathrooms',
                                                   'Balconies', 'Current_Floor',
                                                   'Total_Floors',
                                                   'Bedrooms']),
                                                 ('cat', TargetEncoder(),
                                                  ['Mapped_Area',
                                                   'Property_Age',
                                                   'Furnishing_Status',
                                                   'Area_Type',
                                                   'Property_Status',
                                                   'Facing'])])),
                ('regressor',
                 CatBoostRegressor(depth=6, iterations=1100, l2_leaf_reg=np.float64(1.9622562392303726), learning_rate=np.float64(0.02336501505908804), loss_function='RMSE', random_state=42, subsample=np.float64(0.7523264831222428), verbose=0))])

In [29]:
y_pred_log = pipeline.predict(X_test)

In [30]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
import numpy as np

# R² on log-transformed target
r2 = r2_score(y_test, y_pred_log)

# Convert back to original price scale
y_test_actual = np.expm1(y_test)
y_pred_actual = np.expm1(y_pred_log)

mae = mean_absolute_error(y_test_actual, y_pred_actual)

rmse = np.sqrt(
    mean_squared_error(y_test_actual, y_pred_actual)
)

print(f"R² Score : {r2:.4f}")
print(f"MAE      : {mae:.4f}")
print(f"RMSE     : {rmse:.4f}")

R² Score : 0.8642
MAE      : 15.5532
RMSE     : 24.6776

In [31]:
from hyperopt import hp

space = {
    'iterations': hp.quniform('iterations', 900, 1400, 50),
    'depth': hp.quniform('depth', 5, 8, 1),
    'learning_rate': hp.uniform('learning_rate', 0.01, 0.05),
    'l2_leaf_reg': hp.uniform('l2_leaf_reg', 1, 5),
    'subsample': hp.uniform('subsample', 0.65, 0.90)
}

In [34]:
best = fmin(
    fn=objective,
    space=space,
    algo=tpe.suggest,
    max_evals=100,
    trials=Trials(),
    rstate=np.random.default_rng(42)
)

print(best)

100%|██████████| 100/100 [05:13<00:00,  3.14s/trial, best loss: 0.14433449490677858]
{'depth': np.float64(7.0), 'iterations': np.float64(1300.0), 'l2_leaf_reg': np.float64(2.993158342058905), 'learning_rate': np.float64(0.021734839362835878), 'subsample': np.float64(0.8333885959515775)}

In [35]:
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
import numpy as np

# R² on log-transformed target
r2 = r2_score(y_test, y_pred_log)

# Convert back to original price scale
y_test_actual = np.expm1(y_test)
y_pred_actual = np.expm1(y_pred_log)

mae = mean_absolute_error(y_test_actual, y_pred_actual)

rmse = np.sqrt(
    mean_squared_error(y_test_actual, y_pred_actual)
)

print(f"R² Score : {r2:.4f}")
print(f"MAE      : {mae:.4f}")
print(f"RMSE     : {rmse:.4f}")

R² Score : 0.8642
MAE      : 15.5532
RMSE     : 24.6776

In [36]:
space = {
    'n_estimators': hp.quniform('n_estimators', 200, 1500, 50),
    'max_depth': hp.quniform('max_depth', 3, 12, 1),
    'learning_rate': hp.loguniform('learning_rate', np.log(0.01), np.log(0.3)),
    'subsample': hp.uniform('subsample', 0.6, 1.0),
    'colsample_bytree': hp.uniform('colsample_bytree', 0.6, 1.0),
    'min_child_weight': hp.quniform('min_child_weight', 1, 10, 1),
    'gamma': hp.uniform('gamma', 0, 5),
    'reg_alpha': hp.uniform('reg_alpha', 0, 5),
    'reg_lambda': hp.uniform('reg_lambda', 0, 5)
}

In [37]:
def objective(params):

    model = XGBRegressor(
        n_estimators=int(params['n_estimators']),
        max_depth=int(params['max_depth']),
        learning_rate=params['learning_rate'],
        subsample=params['subsample'],
        colsample_bytree=params['colsample_bytree'],
        min_child_weight=int(params['min_child_weight']),
        gamma=params['gamma'],
        reg_alpha=params['reg_alpha'],
        reg_lambda=params['reg_lambda'],
        random_state=42,
        n_jobs=-1
    )

    pipeline = Pipeline([
        ('preprocessor', preprocessor),
        ('regressor', model)
    ])

    cv = KFold(
        n_splits=5,
        shuffle=True,
        random_state=42
    )

    score = cross_val_score(
        pipeline,
        X,
        y_transformed,
        cv=cv,
        scoring='neg_mean_absolute_error',
        n_jobs=-1
    ).mean()

    return {
        'loss': -score,
        'status': STATUS_OK
    }

In [38]:
trials = Trials()

best = fmin(
    fn=objective,
    space=space,
    algo=tpe.suggest,
    max_evals=100,
    trials=trials,
    rstate=np.random.default_rng(42)
)

print(best)

100%|██████████| 100/100 [00:56<00:00,  1.76trial/s, best loss: 0.14915090962260272]
{'colsample_bytree': np.float64(0.7240262144213081), 'gamma': np.float64(0.01465481841922026), 'learning_rate': np.float64(0.030240369675349123), 'max_depth': np.float64(6.0), 'min_child_weight': np.float64(9.0), 'n_estimators': np.float64(450.0), 'reg_alpha': np.float64(0.8080757350364929), 'reg_lambda': np.float64(1.3717976010091224), 'subsample': np.float64(0.6494271289828449)}

In [39]:
best_xgb = XGBRegressor(
    n_estimators=int(best['n_estimators']),
    max_depth=int(best['max_depth']),
    learning_rate=best['learning_rate'],
    subsample=best['subsample'],
    colsample_bytree=best['colsample_bytree'],
    min_child_weight=int(best['min_child_weight']),
    gamma=best['gamma'],
    reg_alpha=best['reg_alpha'],
    reg_lambda=best['reg_lambda'],
    random_state=42,
    n_jobs=-1
)

In [40]:
pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', best_xgb)
])

pipeline.fit(X_train, y_train)

y_pred_log = pipeline.predict(X_test)

r2 = r2_score(y_test, y_pred_log)

y_test_actual = np.expm1(y_test)
y_pred_actual = np.expm1(y_pred_log)

mae = mean_absolute_error(y_test_actual, y_pred_actual)

rmse = np.sqrt(mean_squared_error(y_test_actual, y_pred_actual))

print(f"R² Score : {r2:.4f}")
print(f"MAE      : {mae:.4f}")
print(f"RMSE     : {rmse:.4f}")

R² Score : 0.8572
MAE      : 17.2129
RMSE     : 29.1229

| Model            | R²         | MAE         | RMSE        |
| ---------------- | ---------- | ----------- | ----------- |
|  Extra Trees   | **0.8791** | **14.4203** | 25.6870     |
|  Random Forest | 0.8782     | 15.1647     | 25.4775     |
|  CatBoost      | 0.8642     | 15.5532     | **24.6776** |
|  XGBoost      | 0.8572     | 17.2129     | 29.1229     |

In [ ]:
import joblib

# 2. Define the preprocessor and pipeline
preprocessor = ColumnTransformer(
    transformers=[
        (
            'num',
            StandardScaler(),
            ['Area', 'Bathrooms', 'Balconies',
             'Current_Floor', 'Total_Floors', 'Bedrooms']
        ),
        (
            'cat',
            TargetEncoder(),
            ['Mapped_Area',
             'Property_Age',
             'Furnishing_Status',
             'Area_Type',
             'Property_Status',
             'Facing']
        )
    ]
)

pipeline = Pipeline([
    ('preprocessor', preprocessor),
    ('regressor', ExtraTreesRegressor(random_state=42))
])

# 3. Apply best hyperparameters found
best_params = {
    'regressor__max_depth': 25,
    'regressor__max_features': None,
    'regressor__min_samples_leaf': 1,
    'regressor__min_samples_split': 7,
    'regressor__n_estimators': 350
}
pipeline.set_params(**best_params)

# 4. Train the model on FULL data 
pipeline.fit(X, y_transformed)

# 5. Save the trained pipeline
joblib.dump(pipeline, "model_full_data.pkl")
print("Model trained on full data and saved as 'model_full_data.pkl'")

Model trained on full data and saved as 'model_full_data.pkl'